#ifndef ACTORS_CHARACTERS_ANIM_IDS_H
#define ACTORS_CHARACTERS_ANIM_IDS_H

// Animation index constants for all character types, plus per-frame action states
// and body part indices used by the tween/skeleton system.
// Migrated from fallen/Headers/animate.h (Stage 4).

// --------------------------------------------------------------------------
// Body dimension constants
// --------------------------------------------------------------------------

// uc_orig: FOOT_HEIGHT (fallen/Headers/animate.h)
#define FOOT_HEIGHT 9
// uc_orig: HAND_HEIGHT (fallen/Headers/animate.h)
#define HAND_HEIGHT 4

// --------------------------------------------------------------------------
// Civilian male animation base index
// --------------------------------------------------------------------------

// uc_orig: CIV_M_START (fallen/Headers/animate.h)
#define CIV_M_START 100
// uc_orig: CIV_M_ANIM_WALK (fallen/Headers/animate.h)
#define CIV_M_ANIM_WALK (CIV_M_START + 2)
// uc_orig: CIV_M_ANIM_RUN (fallen/Headers/animate.h)
#define CIV_M_ANIM_RUN (CIV_M_START + 3)
// uc_orig: CIV_M_ANIM_STAND (fallen/Headers/animate.h)
#define CIV_M_ANIM_STAND (CIV_M_START + 6)
// uc_orig: CIV_M_ANIM_IDLE_START (fallen/Headers/animate.h)
#define CIV_M_ANIM_IDLE_START (CIV_M_START + 5)
// uc_orig: CIV_M_ANIM_IDLE_LOOP (fallen/Headers/animate.h)
#define CIV_M_ANIM_IDLE_LOOP (CIV_M_START + 6)
// uc_orig: CIV_M_ANIM_IDLE_WATCH (fallen/Headers/animate.h)
#define CIV_M_ANIM_IDLE_WATCH (CIV_M_START + 7)
// uc_orig: CIV_M_ANIM_IDLE_END (fallen/Headers/animate.h)
#define CIV_M_ANIM_IDLE_END (CIV_M_START + 8)
// uc_orig: CIV_M_ANIM_SIT_START (fallen/Headers/animate.h)
#define CIV_M_ANIM_SIT_START (CIV_M_START + 9)
// uc_orig: CIV_M_ANIM_SIT_LOOP (fallen/Headers/animate.h)
#define CIV_M_ANIM_SIT_LOOP (CIV_M_START + 10)
// uc_orig: CIV_M_ANIM_SIT_WAIT (fallen/Headers/animate.h)
#define CIV_M_ANIM_SIT_WAIT (CIV_M_START + 11)
// uc_orig: CIV_M_ANIM_SIT_END (fallen/Headers/animate.h)
#define CIV_M_ANIM_SIT_END (CIV_M_START + 12)
// uc_orig: CIV_M_ANIM_SIT_TALK1 (fallen/Headers/animate.h)
#define CIV_M_ANIM_SIT_TALK1 (CIV_M_START + 13)
// uc_orig: CIV_M_ANIM_SIT_TALK2 (fallen/Headers/animate.h)
#define CIV_M_ANIM_SIT_TALK2 (CIV_M_START + 14)
// uc_orig: CIV_M_ANIM_SIT_TALK3 (fallen/Headers/animate.h)
#define CIV_M_ANIM_SIT_TALK3 (CIV_M_START + 15)
// uc_orig: CIV_M_ANIM_HANDS_UP (fallen/Headers/animate.h)
#define CIV_M_ANIM_HANDS_UP (CIV_M_START + 16)
// uc_orig: CIV_M_ANIM_HANDS_UP_LOOP (fallen/Headers/animate.h)
#define CIV_M_ANIM_HANDS_UP_LOOP (CIV_M_START + 17)
// uc_orig: CIV_M_ANIM_HANDS_UP_LIE (fallen/Headers/animate.h)
#define CIV_M_ANIM_HANDS_UP_LIE (CIV_M_START + 18)
// uc_orig: CIV_M_ANIM_TALK1 (fallen/Headers/animate.h)
#define CIV_M_ANIM_TALK1 (CIV_M_START + 19)
// uc_orig: CIV_M_ANIM_TALK2 (fallen/Headers/animate.h)
#define CIV_M_ANIM_TALK2 (CIV_M_START + 20)
// uc_orig: CIV_M_ANIM_TALK3 (fallen/Headers/animate.h)
#define CIV_M_ANIM_TALK3 (CIV_M_START + 21)

// --------------------------------------------------------------------------
// Civilian female animation base index
// --------------------------------------------------------------------------

// uc_orig: CIV_F_START (fallen/Headers/animate.h)
#define CIV_F_START 122
// uc_orig: CIV_F_ANIM_WALK (fallen/Headers/animate.h)
#define CIV_F_ANIM_WALK (CIV_F_START + 2)
// uc_orig: CIV_F_ANIM_IDLE_BREATHE (fallen/Headers/animate.h)
#define CIV_F_ANIM_IDLE_BREATHE (CIV_F_START + 3)
// uc_orig: CIV_F_ANIM_IDLE_START (fallen/Headers/animate.h)
#define CIV_F_ANIM_IDLE_START (CIV_F_START + 4)
// uc_orig: CIV_F_ANIM_IDLE_LOOP (fallen/Headers/animate.h)
#define CIV_F_ANIM_IDLE_LOOP (CIV_F_START + 5)
// uc_orig: CIV_F_ANIM_IDLE_LOOP2 (fallen/Headers/animate.h)
#define CIV_F_ANIM_IDLE_LOOP2 (CIV_F_START + 6)
// uc_orig: CIV_F_ANIM_IDLE_STOP (fallen/Headers/animate.h)
#define CIV_F_ANIM_IDLE_STOP (CIV_F_START + 7)
// uc_orig: CIV_F_ANIM_SIT_IDLE1 (fallen/Headers/animate.h)
#define CIV_F_ANIM_SIT_IDLE1 (CIV_F_START + 8)
// uc_orig: CIV_F_ANIM_SIT_IDLE2 (fallen/Headers/animate.h)
#define CIV_F_ANIM_SIT_IDLE2 (CIV_F_START + 9)
// uc_orig: CIV_F_ANIM_RUN (fallen/Headers/animate.h)
#define CIV_F_ANIM_RUN (CIV_F_START + 10)

// --------------------------------------------------------------------------
// Cop/Roper animation base index and cop-specific clips
// --------------------------------------------------------------------------

// uc_orig: COP_START (fallen/Headers/animate.h)
#define COP_START 200
// uc_orig: COP_ROPER_ANIM_WALK (fallen/Headers/animate.h)
#define COP_ROPER_ANIM_WALK (COP_START + 1)
// uc_orig: COP_ROPER_ANIM_RUN (fallen/Headers/animate.h)
#define COP_ROPER_ANIM_RUN (COP_START + 13)
// uc_orig: COP_ROPER_ANIM_READY (fallen/Headers/animate.h)
#define COP_ROPER_ANIM_READY (COP_START + 2)
// uc_orig: COP_ROPER_ANIM_IDLE1 (fallen/Headers/animate.h)
#define COP_ROPER_ANIM_IDLE1 (COP_START + 4)
// uc_orig: COP_ROPER_ANIM_IDLE2 (fallen/Headers/animate.h)
#define COP_ROPER_ANIM_IDLE2 (COP_START + 11)
// uc_orig: COP_ROPER_ANIM_IDLE3 (fallen/Headers/animate.h)
#define COP_ROPER_ANIM_IDLE3 (COP_START + 14)
// uc_orig: COP_ROPER_ANIM_IDLE4 (fallen/Headers/animate.h)
#define COP_ROPER_ANIM_IDLE4 (COP_START + 15)
// uc_orig: COP_ROPER_ANIM_LADDER_START (fallen/Headers/animate.h)
#define COP_ROPER_ANIM_LADDER_START (COP_START + 19)
// uc_orig: COP_ROPER_ANIM_LADDER_LOOP (fallen/Headers/animate.h)
#define COP_ROPER_ANIM_LADDER_LOOP (COP_START + 20)
// uc_orig: COP_ROPER_ANIM_LADDER_END_L (fallen/Headers/animate.h)
#define COP_ROPER_ANIM_LADDER_END_L (COP_START + 21)
// uc_orig: COP_ROPER_ANIM_LADDER_END_R (fallen/Headers/animate.h)
#define COP_ROPER_ANIM_LADDER_END_R (COP_START + 22)
// uc_orig: COP_ROPER_ANIM_REST (fallen/Headers/animate.h)
#define COP_ROPER_ANIM_REST (COP_START + 24)
// uc_orig: COP_ROPER_ANIM_FIGHT (fallen/Headers/animate.h)
#define COP_ROPER_ANIM_FIGHT (COP_START + 31)
// uc_orig: COP_ROPER_ANIM_LADDER_OFF_BOT (fallen/Headers/animate.h)
#define COP_ROPER_ANIM_LADDER_OFF_BOT (COP_START + 32)

// --------------------------------------------------------------------------
// Roper animation indices (player character clips)
// --------------------------------------------------------------------------

// uc_orig: ROPER_WALK (fallen/Headers/animate.h)
#define ROPER_WALK (1)
// uc_orig: ROPER_PUNCH_CLOSE1 (fallen/Headers/animate.h)
#define ROPER_PUNCH_CLOSE1 (31)
// uc_orig: ROPER_PUNCH_CLOSE2 (fallen/Headers/animate.h)
#define ROPER_PUNCH_CLOSE2 (30)
// uc_orig: ROPER_PUNCH_CLOSE3 (fallen/Headers/animate.h)
#define ROPER_PUNCH_CLOSE3 (32)
// uc_orig: ROPER_ELBOW_CLOSE (fallen/Headers/animate.h)
#define ROPER_ELBOW_CLOSE (3)
// uc_orig: ROPER_DRAW_GUN (fallen/Headers/animate.h)
#define ROPER_DRAW_GUN (2)
// uc_orig: ROPER_SHOOT (fallen/Headers/animate.h)
#define ROPER_SHOOT (3)
// uc_orig: ROPER_RUN (fallen/Headers/animate.h)
#define ROPER_RUN (4)
// uc_orig: ROPER_LAND_ON_FENCE (fallen/Headers/animate.h)
#define ROPER_LAND_ON_FENCE (5)
// uc_orig: ROPER_CLIMB_OVER_FENCE (fallen/Headers/animate.h)
#define ROPER_CLIMB_OVER_FENCE (6)
// uc_orig: ROPER_CLIMB_UP_FENCE (fallen/Headers/animate.h)
#define ROPER_CLIMB_UP_FENCE (7)
// uc_orig: ROPER_STANDING_JUMP (fallen/Headers/animate.h)
#define ROPER_STANDING_JUMP (47)
// uc_orig: ROPER_PULL_UP (fallen/Headers/animate.h)
#define ROPER_PULL_UP (9)
// uc_orig: ROPER_WALK_MEAN (fallen/Headers/animate.h)
#define ROPER_WALK_MEAN (10)
// uc_orig: ROPER_SWING (fallen/Headers/animate.h)
#define ROPER_SWING (11)
// uc_orig: ROPER_ENTER_VAN (fallen/Headers/animate.h)
#define ROPER_ENTER_VAN (12)
// uc_orig: ROPER_EXIT_VAN (fallen/Headers/animate.h)
#define ROPER_EXIT_VAN (13)
// uc_orig: ROPER_AIM_GUN (fallen/Headers/animate.h)
#define ROPER_AIM_GUN (68)
// uc_orig: ROPER_STAND (fallen/Headers/animate.h)
#define ROPER_STAND (15)
// uc_orig: ROPER_DANGLE (fallen/Headers/animate.h)
#define ROPER_DANGLE (16)
// uc_orig: ROPER_ANIM_JUMP (fallen/Headers/animate.h)
#define ROPER_ANIM_JUMP (22)
// uc_orig: ROPER_ANIM_LAND (fallen/Headers/animate.h)
#define ROPER_ANIM_LAND (23)
// uc_orig: ROPER_ANIM_MID_AIR (fallen/Headers/animate.h)
#define ROPER_ANIM_MID_AIR (24)
// uc_orig: ROPER_ANIM_MID_AIR_TWEEN_LEFT (fallen/Headers/animate.h)
#define ROPER_ANIM_MID_AIR_TWEEN_LEFT (23)
// uc_orig: ROPER_ANIM_MID_AIR_TWEEN_RIGHT (fallen/Headers/animate.h)
#define ROPER_ANIM_MID_AIR_TWEEN_RIGHT (23)
// uc_orig: ROPER_JUMP_UP_GRAB (fallen/Headers/animate.h)
#define ROPER_JUMP_UP_GRAB (47)
// uc_orig: ROPER_FLY_GRABBING_LEDGE (fallen/Headers/animate.h)
#define ROPER_FLY_GRABBING_LEDGE (51)
// uc_orig: ROPER_LAND_VERT (fallen/Headers/animate.h)
#define ROPER_LAND_VERT (52)
// uc_orig: ROPER_DEATH_SLIDE (fallen/Headers/animate.h)
#define ROPER_DEATH_SLIDE (59)
// uc_orig: ROPER_CRAWL (fallen/Headers/animate.h)
#define ROPER_CRAWL (26)
// uc_orig: ROPER_FALLING (fallen/Headers/animate.h)
#define ROPER_FALLING (48)
// uc_orig: ROPER_FIGHT_IDLE (fallen/Headers/animate.h)
#define ROPER_FIGHT_IDLE (49)
// uc_orig: ROPER_FIGHT_RECOIL (fallen/Headers/animate.h)
#define ROPER_FIGHT_RECOIL (50)
// uc_orig: ROPER_KICK_DOOR (fallen/Headers/animate.h)
#define ROPER_KICK_DOOR (46)
// uc_orig: ROPER_IDLE_CROUCH (fallen/Headers/animate.h)
#define ROPER_IDLE_CROUCH (54)
// uc_orig: ROPER_CROUCH_DOWN (fallen/Headers/animate.h)
#define ROPER_CROUCH_DOWN (53)
// uc_orig: ROPER_PICKUP (fallen/Headers/animate.h)
#define ROPER_PICKUP (38)
// uc_orig: ROPER_THROW_1H (fallen/Headers/animate.h)
#define ROPER_THROW_1H (42)
// uc_orig: ROPER_FOLDARMS (fallen/Headers/animate.h)
#define ROPER_FOLDARMS (62)
// uc_orig: ROPER_ARMSFOLDED (fallen/Headers/animate.h)
#define ROPER_ARMSFOLDED (64)
// uc_orig: ROPER_TO_FIGHT (fallen/Headers/animate.h)
#define ROPER_TO_FIGHT (72)
// uc_orig: ROPER_MOUNT_LADDER (fallen/Headers/animate.h)
#define ROPER_MOUNT_LADDER (56)
// uc_orig: ROPER_ON_LADDER (fallen/Headers/animate.h)
#define ROPER_ON_LADDER (57)
// uc_orig: ROPER_OFF_LADDER_TOP (fallen/Headers/animate.h)
#define ROPER_OFF_LADDER_TOP (58)
// uc_orig: ROPER_TRAVERSE_LEFT (fallen/Headers/animate.h)
#define ROPER_TRAVERSE_LEFT (60)
// uc_orig: ROPER_TRAVERSE_RIGHT (fallen/Headers/animate.h)
#define ROPER_TRAVERSE_RIGHT (61)
// uc_orig: ROPER_ROTATE_LEFT (fallen/Headers/animate.h)
#define ROPER_ROTATE_LEFT (65)
// uc_orig: ROPER_ROTATE_RIGHT (fallen/Headers/animate.h)
#define ROPER_ROTATE_RIGHT (66)
// uc_orig: ROPER_FIGHT_LEFT (fallen/Headers/animate.h)
#define ROPER_FIGHT_LEFT (75)
// uc_orig: ROPER_FIGHT_RIGHT (fallen/Headers/animate.h)
#define ROPER_FIGHT_RIGHT (76)
// uc_orig: ROPER_FIGHT_FORWARD (fallen/Headers/animate.h)
#define ROPER_FIGHT_FORWARD (73)
// uc_orig: ROPER_FIGHT_BACK (fallen/Headers/animate.h)
#define ROPER_FIGHT_BACK (74)
// uc_orig: ROPER_BIKE_MOUNT (fallen/Headers/animate.h)
#define ROPER_BIKE_MOUNT (33)
// uc_orig: ROPER_BIKE_RIDE (fallen/Headers/animate.h)
#define ROPER_BIKE_RIDE (69)
// uc_orig: ROPER_BIKE_LEAN_LEFT (fallen/Headers/animate.h)
#define ROPER_BIKE_LEAN_LEFT (70)
// uc_orig: ROPER_BIKE_LEAN_RIGHT (fallen/Headers/animate.h)
#define ROPER_BIKE_LEAN_RIGHT (71)

// --------------------------------------------------------------------------
// Thug animations
// --------------------------------------------------------------------------

// uc_orig: THUG_ANIM_WALK (fallen/Headers/animate.h)
#define THUG_ANIM_WALK (2)
// uc_orig: THUG_ANIM_RUN (fallen/Headers/animate.h)
#define THUG_ANIM_RUN (5)
// uc_orig: THUG_ANIM_IDLE1 (fallen/Headers/animate.h)
#define THUG_ANIM_IDLE1 (8)
// uc_orig: THUG_ANIM_IDLE2 (fallen/Headers/animate.h)
#define THUG_ANIM_IDLE2 (9)
// uc_orig: THUG_ANIM_FIGHT_IDLE (fallen/Headers/animate.h)
#define THUG_ANIM_FIGHT_IDLE (41)

// --------------------------------------------------------------------------
// Civilian character animations (shared set)
// --------------------------------------------------------------------------

// uc_orig: CIV_ANIM_WALK (fallen/Headers/animate.h)
#define CIV_ANIM_WALK (2)
// uc_orig: CIV_ANIM_WANKER (fallen/Headers/animate.h)
#define CIV_ANIM_WANKER (13)
// uc_orig: CIV_ANIM_ENTER_TAXI (fallen/Headers/animate.h)
#define CIV_ANIM_ENTER_TAXI (27)
// uc_orig: CIV_ANIM_SIT (fallen/Headers/animate.h)
#define CIV_ANIM_SIT (28)
// uc_orig: CIV_ANIM_READ_PAPER1 (fallen/Headers/animate.h)
#define CIV_ANIM_READ_PAPER1 (29)
// uc_orig: CIV_ANIM_READ_PAPER2 (fallen/Headers/animate.h)
#define CIV_ANIM_READ_PAPER2 (30)
// uc_orig: CIV_ANIM_IDLE_BREATHE (fallen/Headers/animate.h)
#define CIV_ANIM_IDLE_BREATHE (30)
// uc_orig: CIV_ANIM_IDLE_PHONE_ANSWER (fallen/Headers/animate.h)
#define CIV_ANIM_IDLE_PHONE_ANSWER (31)
// uc_orig: CIV_ANIM_IDLE_PHONE_TALK (fallen/Headers/animate.h)
#define CIV_ANIM_IDLE_PHONE_TALK (32)
// uc_orig: CIV_FIGHT_IDLE (fallen/Headers/animate.h)
#define CIV_FIGHT_IDLE (46)
// uc_orig: CIV_BLOCK (fallen/Headers/animate.h)
#define CIV_BLOCK (45)
// uc_orig: CIV_ANIM_DANCE_BOOGIE (fallen/Headers/animate.h)
#define CIV_ANIM_DANCE_BOOGIE (52)
// uc_orig: CIV_ANIM_DANCE_WOOGIE (fallen/Headers/animate.h)
#define CIV_ANIM_DANCE_WOOGIE (58)
// uc_orig: CIV_ANIM_DANCE_HEADBANG (fallen/Headers/animate.h)
#define CIV_ANIM_DANCE_HEADBANG (55)
// uc_orig: CIV_ANIM_WARM_HANDS (fallen/Headers/animate.h)
#define CIV_ANIM_WARM_HANDS (53)
// uc_orig: CIV_ANIM_HANDS_UP (fallen/Headers/animate.h)
#define CIV_ANIM_HANDS_UP (56)
// uc_orig: CIV_ANIM_HANDS_UP_LOOP (fallen/Headers/animate.h)
#define CIV_ANIM_HANDS_UP_LOOP (57)

// --------------------------------------------------------------------------
// Generic hit and knock-out animations
// --------------------------------------------------------------------------

// uc_orig: ANIM_HEAD_HIT_SMALL (fallen/Headers/animate.h)
#define ANIM_HEAD_HIT_SMALL (26)
// uc_orig: ANIM_HEAD_HIT_BIG (fallen/Headers/animate.h)
#define ANIM_HEAD_HIT_BIG (22)
// uc_orig: ANIM_HEAD_HIT_BEHIND (fallen/Headers/animate.h)
#define ANIM_HEAD_HIT_BEHIND (28)
// uc_orig: ANIM_GUT_HIT_BIG (fallen/Headers/animate.h)
#define ANIM_GUT_HIT_BIG (24)
// uc_orig: ANIM_GUT_HIT_SMALL (fallen/Headers/animate.h)
#define ANIM_GUT_HIT_SMALL (27)
// uc_orig: ANIM_GUT_HIT_BIG_BEHIND (fallen/Headers/animate.h)
#define ANIM_GUT_HIT_BIG_BEHIND (40)
// uc_orig: ANIM_KO_BEHIND_BIG (fallen/Headers/animate.h)
#define ANIM_KO_BEHIND_BIG (109)
// uc_orig: ANIM_KO_BEHIND_BIG_GU (fallen/Headers/animate.h)
#define ANIM_KO_BEHIND_BIG_GU (110)
// uc_orig: ANIM_KO_BACK (fallen/Headers/animate.h)
#define ANIM_KO_BACK (33)
// uc_orig: ANIM_KO_BACK_GU (fallen/Headers/animate.h)
#define ANIM_KO_BACK_GU (34)

// --------------------------------------------------------------------------
// Shared character animation indices (Darci/Roper/NPC shared clip set)
// --------------------------------------------------------------------------

// uc_orig: ANIM_RUN (fallen/Headers/animate.h)
#define ANIM_RUN (119)
// uc_orig: ANIM_WALK (fallen/Headers/animate.h)
#define ANIM_WALK (20)
// uc_orig: ANIM_STAND_HIP (fallen/Headers/animate.h)
#define ANIM_STAND_HIP (2)
// uc_orig: ANIM_STAND_READY (fallen/Headers/animate.h)
#define ANIM_STAND_READY (3)
// uc_orig: ANIM_KICK_ROUND1 (fallen/Headers/animate.h)
#define ANIM_KICK_ROUND1 (8)
// uc_orig: ANIM_PUNCH1 (fallen/Headers/animate.h)
#define ANIM_PUNCH1 (19)
// uc_orig: ANIM_PULL_UP (fallen/Headers/animate.h)
#define ANIM_PULL_UP (48)
// uc_orig: ANIM_UP_LADDER (fallen/Headers/animate.h)
#define ANIM_UP_LADDER (14)
// uc_orig: ANIM_VAULT (fallen/Headers/animate.h)
#define ANIM_VAULT (16)
// uc_orig: ANIM_SIDLE (fallen/Headers/animate.h)
#define ANIM_SIDLE (18)
// uc_orig: ANIM_FALLING (fallen/Headers/animate.h)
#define ANIM_FALLING (51)
// uc_orig: ANIM_FALLING_QUEUED (fallen/Headers/animate.h)
#define ANIM_FALLING_QUEUED (206)
// uc_orig: ANIM_FALLING_AK (fallen/Headers/animate.h)
#define ANIM_FALLING_AK (390)
// uc_orig: ANIM_FALLING_QUEUED_AK (fallen/Headers/animate.h)
#define ANIM_FALLING_QUEUED_AK (382)
// uc_orig: ANIM_STANDING_JUMP (fallen/Headers/animate.h)
#define ANIM_STANDING_JUMP (203)
// uc_orig: ANIM_STANDING_JUMP_AK (fallen/Headers/animate.h)
#define ANIM_STANDING_JUMP_AK (380)
// uc_orig: ANIM_LAND_VERT_AK (fallen/Headers/animate.h)
#define ANIM_LAND_VERT_AK (381)
// uc_orig: ANIM_FALL_VERT_AK (fallen/Headers/animate.h)
#define ANIM_FALL_VERT_AK (382)
// uc_orig: ANIM_FLY_GRABBING_LEDGE (fallen/Headers/animate.h)
#define ANIM_FLY_GRABBING_LEDGE (52)
// uc_orig: ANIM_JUMP_UP_GRAB (fallen/Headers/animate.h)
#define ANIM_JUMP_UP_GRAB (12)
// uc_orig: ANIM_LAND_VERT (fallen/Headers/animate.h)
#define ANIM_LAND_VERT (204)
// uc_orig: ANIM_MOUNT_LADDER (fallen/Headers/animate.h)
#define ANIM_MOUNT_LADDER (13)
// uc_orig: ANIM_ON_LADDER (fallen/Headers/animate.h)
#define ANIM_ON_LADDER (14)
// uc_orig: ANIM_OFF_LADDER_TOP (fallen/Headers/animate.h)
#define ANIM_OFF_LADDER_TOP (55)
// uc_orig: ANIM_OFF_LADDER_BOT (fallen/Headers/animate.h)
#define ANIM_OFF_LADDER_BOT (56)
// uc_orig: ANIM_FIGHT_READY (fallen/Headers/animate.h)
#define ANIM_FIGHT_READY (25)
// uc_orig: ANIM_PUNCH2 (fallen/Headers/animate.h)
#define ANIM_PUNCH2 (35)
// uc_orig: ANIM_KICK2 (fallen/Headers/animate.h)
#define ANIM_KICK2 (36)
// uc_orig: ANIM_PUNCH3 (fallen/Headers/animate.h)
#define ANIM_PUNCH3 (39)
// uc_orig: ANIM_LAND_ON_FENCE (fallen/Headers/animate.h)
#define ANIM_LAND_ON_FENCE (57)
// uc_orig: ANIM_CLIMB_UP_FENCE (fallen/Headers/animate.h)
#define ANIM_CLIMB_UP_FENCE (45)
// uc_orig: ANIM_CLIMB_RIGHT_FENCE (fallen/Headers/animate.h)
#define ANIM_CLIMB_RIGHT_FENCE (43)
// uc_orig: ANIM_CLIMB_LEFT_FENCE (fallen/Headers/animate.h)
#define ANIM_CLIMB_LEFT_FENCE (42)
// uc_orig: ANIM_CLIMB_OVER_FENCE (fallen/Headers/animate.h)
#define ANIM_CLIMB_OVER_FENCE (58)
// uc_orig: ANIM_HAND_OVER_HAND (fallen/Headers/animate.h)
#define ANIM_HAND_OVER_HAND (37)
// uc_orig: ANIM_DEATH_SLIDE (fallen/Headers/animate.h)
#define ANIM_DEATH_SLIDE (68)
// uc_orig: ANIM_FALL_LONG (fallen/Headers/animate.h)
#define ANIM_FALL_LONG (47)
// uc_orig: ANIM_STEP_LEFT (fallen/Headers/animate.h)
#define ANIM_STEP_LEFT (59)
// uc_orig: ANIM_STEP_RIGHT (fallen/Headers/animate.h)
#define ANIM_STEP_RIGHT (60)
// uc_orig: ANIM_LANDED_ON_FENCE (fallen/Headers/animate.h)
#define ANIM_LANDED_ON_FENCE (62)
// uc_orig: ANIM_FLIP_LEFT (fallen/Headers/animate.h)
#define ANIM_FLIP_LEFT (91)
// uc_orig: ANIM_FLIP_RIGHT (fallen/Headers/animate.h)
#define ANIM_FLIP_RIGHT (92)
// uc_orig: ANIM_FLIP_RIGHT_CONT (fallen/Headers/animate.h)
#define ANIM_FLIP_RIGHT_CONT (93)
// uc_orig: ANIM_FLIP_LEFT_CONT (fallen/Headers/animate.h)
#define ANIM_FLIP_LEFT_CONT (94)
// uc_orig: ANIM_IDLE_SCRATCH1 (fallen/Headers/animate.h)
#define ANIM_IDLE_SCRATCH1 (77)
// uc_orig: ANIM_IDLE_SCRATCH2 (fallen/Headers/animate.h)
#define ANIM_IDLE_SCRATCH2 (78)
// uc_orig: ANIM_NECK_SNAP (fallen/Headers/animate.h)
#define ANIM_NECK_SNAP (88)
// uc_orig: ANIM_ENTER_CAR (fallen/Headers/animate.h)
#define ANIM_ENTER_CAR (89)
// uc_orig: ANIM_EXIT_CAR (fallen/Headers/animate.h)
#define ANIM_EXIT_CAR (90)
// uc_orig: ANIM_SNEAK (fallen/Headers/animate.h)
#define ANIM_SNEAK (86)
// uc_orig: ANIM_BSTEP (fallen/Headers/animate.h)
#define ANIM_BSTEP (69)
// uc_orig: ANIM_LAND_STAND (fallen/Headers/animate.h)
#define ANIM_LAND_STAND (96)
// uc_orig: ANIM_RUN_JUMP_LEFT_AK (fallen/Headers/animate.h)
#define ANIM_RUN_JUMP_LEFT_AK (269)
// uc_orig: ANIM_RUN_JUMP_LEFT (fallen/Headers/animate.h)
#define ANIM_RUN_JUMP_LEFT (54)
// uc_orig: ANIM_RUN_JUMP_RIGHT (fallen/Headers/animate.h)
#define ANIM_RUN_JUMP_RIGHT (46)
// uc_orig: ANIM_SIT (fallen/Headers/animate.h)
#define ANIM_SIT (100)
// uc_orig: ANIM_DESPAIR (fallen/Headers/animate.h)
#define ANIM_DESPAIR (101)
// uc_orig: ANIM_STAND_UP (fallen/Headers/animate.h)
#define ANIM_STAND_UP (103)
// uc_orig: ANIM_SNAP_KNECK (fallen/Headers/animate.h)
#define ANIM_SNAP_KNECK (88)
// uc_orig: ANIM_LAND_RIGHT (fallen/Headers/animate.h)
#define ANIM_LAND_RIGHT (53)
// uc_orig: ANIM_LAND_RIGHT_AK (fallen/Headers/animate.h)
#define ANIM_LAND_RIGHT_AK (270)
// uc_orig: ANIM_MID_AIR_TWEEN_LEFT_AK (fallen/Headers/animate.h)
#define ANIM_MID_AIR_TWEEN_LEFT_AK (268)
// uc_orig: ANIM_MID_AIR_TWEEN_LEFT (fallen/Headers/animate.h)
#define ANIM_MID_AIR_TWEEN_LEFT (122)
// uc_orig: ANIM_MID_AIR_TWEEN_RIGHT (fallen/Headers/animate.h)
#define ANIM_MID_AIR_TWEEN_RIGHT (122)
// uc_orig: ANIM_LOB2 (fallen/Headers/animate.h)
#define ANIM_LOB2 (87)
// uc_orig: ANIM_HOSTAGE_STAND (fallen/Headers/animate.h)
#define ANIM_HOSTAGE_STAND (99)
// uc_orig: ANIM_HOSTAGE_SIT (fallen/Headers/animate.h)
#define ANIM_HOSTAGE_SIT (100)
// uc_orig: ANIM_HOSTAGE_DESPAIR (fallen/Headers/animate.h)
#define ANIM_HOSTAGE_DESPAIR (101)
// uc_orig: ANIM_HOSTAGE_READY (fallen/Headers/animate.h)
#define ANIM_HOSTAGE_READY (102)
// uc_orig: ANIM_HOSTAGE_RELEASE (fallen/Headers/animate.h)
#define ANIM_HOSTAGE_RELEASE (103)
// uc_orig: ANIM_SHOTGUN_DRAW (fallen/Headers/animate.h)
#define ANIM_SHOTGUN_DRAW (81)
// uc_orig: ANIM_SHOTGUN_IDLE_OLD (fallen/Headers/animate.h)
#define ANIM_SHOTGUN_IDLE_OLD (82)
// uc_orig: ANIM_SHOTGUN_SHOOT (fallen/Headers/animate.h)
#define ANIM_SHOTGUN_SHOOT (83)
// uc_orig: ANIN_SHOTGUN_WHIP (fallen/Headers/animate.h)
#define ANIN_SHOTGUN_WHIP (84)
// uc_orig: ANIM_SHOTGUN_WALK (fallen/Headers/animate.h)
#define ANIM_SHOTGUN_WALK (85)
// uc_orig: ANIM_BACK_FLIP (fallen/Headers/animate.h)
#define ANIM_BACK_FLIP (105)
// uc_orig: ANIM_FORWARD_JUMP (fallen/Headers/animate.h)
#define ANIM_FORWARD_JUMP (112)
// uc_orig: ANIM_WALL_KICK (fallen/Headers/animate.h)
#define ANIM_WALL_KICK (117)
// uc_orig: ANIM_RUN_JUMP_MLEFT (fallen/Headers/animate.h)
#define ANIM_RUN_JUMP_MLEFT (118)
// uc_orig: ANIM_BACK_HOP (fallen/Headers/animate.h)
#define ANIM_BACK_HOP (121)
// uc_orig: ANIM_BREATHE (fallen/Headers/animate.h)
#define ANIM_BREATHE (124)
// uc_orig: ANIM_KICK3 (fallen/Headers/animate.h)
#define ANIM_KICK3 (104)
// uc_orig: ANIM_GRAPPLING_HOOK_PICKUP (fallen/Headers/animate.h)
#define ANIM_GRAPPLING_HOOK_PICKUP (140)
// uc_orig: ANIM_GRAPPLING_HOOK_WINDUP (fallen/Headers/animate.h)
#define ANIM_GRAPPLING_HOOK_WINDUP (137)
// uc_orig: ANIM_GRAPPLING_HOOK_RELEASE (fallen/Headers/animate.h)
#define ANIM_GRAPPLING_HOOK_RELEASE (138)
// uc_orig: ANIM_CAN_PICKUP (fallen/Headers/animate.h)
#define ANIM_CAN_PICKUP (64)
// uc_orig: ANIM_CAN_RELEASE (fallen/Headers/animate.h)
#define ANIM_CAN_RELEASE (65)
// uc_orig: ANIM_FATAL_FALL (fallen/Headers/animate.h)
#define ANIM_FATAL_FALL (80)
// uc_orig: ANIM_PLUNGE_BACKWARDS (fallen/Headers/animate.h)
#define ANIM_PLUNGE_BACKWARDS (128)
// uc_orig: ANIM_PLUNGE_FORWARDS (fallen/Headers/animate.h)
#define ANIM_PLUNGE_FORWARDS (129)
// uc_orig: ANIM_TRAVERSE_LEFT (fallen/Headers/animate.h)
#define ANIM_TRAVERSE_LEFT (130)
// uc_orig: ANIM_TRAVERSE_RIGHT (fallen/Headers/animate.h)
#define ANIM_TRAVERSE_RIGHT (131)
// uc_orig: ANIM_TURN90_LEFT (fallen/Headers/animate.h)
#define ANIM_TURN90_LEFT (132)
// uc_orig: ANIM_TURN90_RIGHT (fallen/Headers/animate.h)
#define ANIM_TURN90_RIGHT (133)
// uc_orig: ANIM_BUTTON (fallen/Headers/animate.h)
#define ANIM_BUTTON (134)
// uc_orig: ANIM_LEVER (fallen/Headers/animate.h)
#define ANIM_LEVER (135)
// uc_orig: ANIM_BATMAN (fallen/Headers/animate.h)
#define ANIM_BATMAN (139)
// uc_orig: ANIM_PLUNGE_BACK_SLAM (fallen/Headers/animate.h)
#define ANIM_PLUNGE_BACK_SLAM (140)
// uc_orig: ANIM_PLUNGE_FRONT_SLAM (fallen/Headers/animate.h)
#define ANIM_PLUNGE_FRONT_SLAM (141)
// uc_orig: ANIM_GET_DOWN (fallen/Headers/animate.h)
#define ANIM_GET_DOWN (142)
// uc_orig: ANIM_CROUCH (fallen/Headers/animate.h)
#define ANIM_CROUCH (143)
// uc_orig: ANIM_CRAWL (fallen/Headers/animate.h)
#define ANIM_CRAWL (144)
// uc_orig: ANIM_PUNCH_COMBO1 (fallen/Headers/animate.h)
#define ANIM_PUNCH_COMBO1 (146)
// uc_orig: ANIM_PUNCH_COMBO2 (fallen/Headers/animate.h)
#define ANIM_PUNCH_COMBO2 (147)
// uc_orig: ANIM_PUNCH_COMBO3 (fallen/Headers/animate.h)
#define ANIM_PUNCH_COMBO3 (148)
// uc_orig: ANIM_PUNCH_COMBO3B (fallen/Headers/animate.h)
#define ANIM_PUNCH_COMBO3B (149)
// uc_orig: ANIM_PUNCH_RETURN1 (fallen/Headers/animate.h)
#define ANIM_PUNCH_RETURN1 (150)
// uc_orig: ANIM_PUNCH_RETURN2 (fallen/Headers/animate.h)
#define ANIM_PUNCH_RETURN2 (151)
// uc_orig: ANIM_KICK_COMBO1 (fallen/Headers/animate.h)
#define ANIM_KICK_COMBO1 (154)
// uc_orig: ANIM_KICK_COMBO2 (fallen/Headers/animate.h)
#define ANIM_KICK_COMBO2 (155)
// uc_orig: ANIM_KICK_COMBO3 (fallen/Headers/animate.h)
#define ANIM_KICK_COMBO3 (156)
// uc_orig: ANIM_KICK_RETURN1 (fallen/Headers/animate.h)
#define ANIM_KICK_RETURN1 (157)
// uc_orig: ANIM_KICK_RETURN2 (fallen/Headers/animate.h)
#define ANIM_KICK_RETURN2 (158)
// uc_orig: ANIM_FIGHT (fallen/Headers/animate.h)
#define ANIM_FIGHT (159)
// uc_orig: ANIM_KICK_NS (fallen/Headers/animate.h)
#define ANIM_KICK_NS (161)
// uc_orig: ANIM_KICK_LEFT (fallen/Headers/animate.h)
#define ANIM_KICK_LEFT (162)
// uc_orig: ANIM_KICK_RIGHT (fallen/Headers/animate.h)
#define ANIM_KICK_RIGHT (262)
// uc_orig: ANIM_KICK_NEAR (fallen/Headers/animate.h)
#define ANIM_KICK_NEAR (263)
// uc_orig: ANIM_PUNCH_BEHIND (fallen/Headers/animate.h)
#define ANIM_PUNCH_BEHIND (163)
// uc_orig: ANIM_KICK_BEHIND (fallen/Headers/animate.h)
#define ANIM_KICK_BEHIND (164)
// uc_orig: ANIM_BLOCK_HIGH (fallen/Headers/animate.h)
#define ANIM_BLOCK_HIGH (165)
// uc_orig: ANIM_HIT_FRONT_HI (fallen/Headers/animate.h)
#define ANIM_HIT_FRONT_HI (166)
// uc_orig: ANIM_HIT_FRONT_MID (fallen/Headers/animate.h)
#define ANIM_HIT_FRONT_MID (167)
// uc_orig: ANIM_HIT_BACK_HI (fallen/Headers/animate.h)
#define ANIM_HIT_BACK_HI (168)
// uc_orig: ANIM_HIT_BACK_MID (fallen/Headers/animate.h)
#define ANIM_HIT_BACK_MID (169)
// uc_orig: ANIM_KD_FRONT_MID (fallen/Headers/animate.h)
#define ANIM_KD_FRONT_MID (170)
// uc_orig: ANIM_KD_FRONT_HI (fallen/Headers/animate.h)
#define ANIM_KD_FRONT_HI (171)
// uc_orig: ANIM_KD_BACK_MID (fallen/Headers/animate.h)
#define ANIM_KD_BACK_MID (172)
// uc_orig: ANIM_KD_BACK_HI (fallen/Headers/animate.h)
#define ANIM_KD_BACK_HI (173)
// uc_orig: ANIM_KD_BACK_LOW (fallen/Headers/animate.h)
#define ANIM_KD_BACK_LOW (174)
// uc_orig: ANIM_KD_FRONT_LOW (fallen/Headers/animate.h)
#define ANIM_KD_FRONT_LOW (175)
// uc_orig: ANIM_KD_FRONT_LAND (fallen/Headers/animate.h)
#define ANIM_KD_FRONT_LAND (176)
// uc_orig: ANIM_KD_BACK_LAND (fallen/Headers/animate.h)
#define ANIM_KD_BACK_LAND (177)
// uc_orig: ANIM_FIGHT_STEP_N (fallen/Headers/animate.h)
#define ANIM_FIGHT_STEP_N (178)
// uc_orig: ANIM_FIGHT_STEP_S (fallen/Headers/animate.h)
#define ANIM_FIGHT_STEP_S (179)
// uc_orig: ANIM_FIGHT_STEP_E (fallen/Headers/animate.h)
#define ANIM_FIGHT_STEP_E (180)
// uc_orig: ANIM_FIGHT_STEP_W (fallen/Headers/animate.h)
#define ANIM_FIGHT_STEP_W (181)
// uc_orig: ANIM_PUNCH_COMBO2b (fallen/Headers/animate.h)
#define ANIM_PUNCH_COMBO2b (185)
// uc_orig: ANIM_PUNCH_COMBO3b (fallen/Headers/animate.h)
#define ANIM_PUNCH_COMBO3b (186)
// uc_orig: ANIM_KICK_COMBO3b (fallen/Headers/animate.h)
#define ANIM_KICK_COMBO3b (187)
// uc_orig: ANIM_FIGHT_STOMP (fallen/Headers/animate.h)
#define ANIM_FIGHT_STOMP (184)
// uc_orig: ANIM_FIGHT_STOMPED_BACK (fallen/Headers/animate.h)
#define ANIM_FIGHT_STOMPED_BACK (188)
// uc_orig: ANIM_FIGHT_STOMPED_FRONT (fallen/Headers/animate.h)
#define ANIM_FIGHT_STOMPED_FRONT (189)
// uc_orig: ANIM_IDLE_CROUTCH (fallen/Headers/animate.h)
#define ANIM_IDLE_CROUTCH (222)
// uc_orig: ANIM_CROUTCH_DOWN (fallen/Headers/animate.h)
#define ANIM_CROUTCH_DOWN (143)
// uc_orig: ANIM_ROTATE_L (fallen/Headers/animate.h)
#define ANIM_ROTATE_L (193)
// uc_orig: ANIM_ROTATE_R (fallen/Headers/animate.h)
#define ANIM_ROTATE_R (194)
// uc_orig: ANIM_YOMP (fallen/Headers/animate.h)
#define ANIM_YOMP (198)
// uc_orig: ANIM_BAT_HIT1 (fallen/Headers/animate.h)
#define ANIM_BAT_HIT1 (199)
// uc_orig: ANIM_BAT_HIT1_RET (fallen/Headers/animate.h)
#define ANIM_BAT_HIT1_RET (240)
// uc_orig: ANIM_BAT_HIT2 (fallen/Headers/animate.h)
#define ANIM_BAT_HIT2 (200)
// uc_orig: ANIM_BAT_IDLE (fallen/Headers/animate.h)
#define ANIM_BAT_IDLE (201)
// uc_orig: ANIM_BAT_BLOCK (fallen/Headers/animate.h)
#define ANIM_BAT_BLOCK (202)
// uc_orig: ANIM_BAT_DRAW (fallen/Headers/animate.h)
#define ANIM_BAT_DRAW (245)
// uc_orig: ANIM_SHOTGUN_WHIP1 (fallen/Headers/animate.h)
#define ANIM_SHOTGUN_WHIP1 (208)
// uc_orig: ANIM_SHOTGUN_WHIP2 (fallen/Headers/animate.h)
#define ANIM_SHOTGUN_WHIP2 (209)
// uc_orig: ANIM_SHOTGUN_FIRE (fallen/Headers/animate.h)
#define ANIM_SHOTGUN_FIRE (210)
// uc_orig: ANIM_SHOTGUN_WHIP3 (fallen/Headers/animate.h)
#define ANIM_SHOTGUN_WHIP3 (211)
// uc_orig: ANIM_SHOTGUN_STAND (fallen/Headers/animate.h)
#define ANIM_SHOTGUN_STAND (212)
// uc_orig: ANIM_SHOTGUN_BLOCK (fallen/Headers/animate.h)
#define ANIM_SHOTGUN_BLOCK (213)
// uc_orig: ANIM_SHOTGUN_AIM (fallen/Headers/animate.h)
#define ANIM_SHOTGUN_AIM (293)
// uc_orig: ANIM_SLIDER_START (fallen/Headers/animate.h)
#define ANIM_SLIDER_START (216)
// uc_orig: ANIM_SLIDER_END (fallen/Headers/animate.h)
#define ANIM_SLIDER_END (217)
// uc_orig: ANIM_SLIDER_HOLD (fallen/Headers/animate.h)
#define ANIM_SLIDER_HOLD (218)
// uc_orig: ANIM_LEG_SWEEP (fallen/Headers/animate.h)
#define ANIM_LEG_SWEEP (219)
// uc_orig: ANIM_FIGHT_SHUFFLE (fallen/Headers/animate.h)
#define ANIM_FIGHT_SHUFFLE (221)
// uc_orig: ANIM_DANGLE (fallen/Headers/animate.h)
#define ANIM_DANGLE (223)
// uc_orig: ANIM_GRAB_ARM (fallen/Headers/animate.h)
#define ANIM_GRAB_ARM (226)
// uc_orig: ANIM_GRAB_ARMV (fallen/Headers/animate.h)
#define ANIM_GRAB_ARMV (227)
// uc_orig: ANIM_GRAB_ARM_THROW (fallen/Headers/animate.h)
#define ANIM_GRAB_ARM_THROW (228)
// uc_orig: ANIM_GRAB_ARM_THROWV (fallen/Headers/animate.h)
#define ANIM_GRAB_ARM_THROWV (229)
// uc_orig: ANIM_GRAB_ARM_KNEE1 (fallen/Headers/animate.h)
#define ANIM_GRAB_ARM_KNEE1 (230)
// uc_orig: ANIM_GRAB_ARM_KNEE1V (fallen/Headers/animate.h)
#define ANIM_GRAB_ARM_KNEE1V (231)
// uc_orig: ANIM_GRAB_ARM_KNEE2 (fallen/Headers/animate.h)
#define ANIM_GRAB_ARM_KNEE2 (232)
// uc_orig: ANIM_GRAB_ARM_KNEE2V (fallen/Headers/animate.h)
#define ANIM_GRAB_ARM_KNEE2V (233)
// uc_orig: ANIM_GRAB_ARM_ESCAPE (fallen/Headers/animate.h)
#define ANIM_GRAB_ARM_ESCAPE (234)
// uc_orig: ANIM_GRAB_ARM_ESCAPEV (fallen/Headers/animate.h)
#define ANIM_GRAB_ARM_ESCAPEV (235)
// uc_orig: ANIM_BIG_LAND (fallen/Headers/animate.h)
#define ANIM_BIG_LAND (225)
// uc_orig: ANIM_YOMP_START (fallen/Headers/animate.h)
#define ANIM_YOMP_START (238)
// uc_orig: ANIM_BIKE_LEAN_LEFT_FOOT (fallen/Headers/animate.h)
#define ANIM_BIKE_LEAN_LEFT_FOOT (287)
// uc_orig: ANIM_BIKE_LEAN_RIGHT_FOOT (fallen/Headers/animate.h)
#define ANIM_BIKE_LEAN_RIGHT_FOOT (288)
// uc_orig: ANIM_BIKE_LEAN_LEFT (fallen/Headers/animate.h)
#define ANIM_BIKE_LEAN_LEFT (252)
// uc_orig: ANIM_BIKE_LEAN_RIGHT (fallen/Headers/animate.h)
#define ANIM_BIKE_LEAN_RIGHT (250)
// uc_orig: ANIM_BIKE_LEAN (fallen/Headers/animate.h)
#define ANIM_BIKE_LEAN (248)
// uc_orig: ANIM_BIKE_MOUNT (fallen/Headers/animate.h)
#define ANIM_BIKE_MOUNT (236)
// uc_orig: ANIM_BIKE_RIDE (fallen/Headers/animate.h)
#define ANIM_BIKE_RIDE (237)
// uc_orig: ANIM_LEG_SWEEP_LOW (fallen/Headers/animate.h)
#define ANIM_LEG_SWEEP_LOW (242)
// uc_orig: ANIM_WIRE_SLIDE_PULLUP (fallen/Headers/animate.h)
#define ANIM_WIRE_SLIDE_PULLUP (246)
// uc_orig: ANIM_WIRE_SLIDE_HANG (fallen/Headers/animate.h)
#define ANIM_WIRE_SLIDE_HANG (247)
// uc_orig: ANIM_BLOCK_LOW (fallen/Headers/animate.h)
#define ANIM_BLOCK_LOW (112)
// uc_orig: ANIM_AK_AIM (fallen/Headers/animate.h)
#define ANIM_AK_AIM (253)
// uc_orig: ANIM_AK_FIRE (fallen/Headers/animate.h)
#define ANIM_AK_FIRE (254)
// uc_orig: ANIM_AK_JOG (fallen/Headers/animate.h)
#define ANIM_AK_JOG (266)
// uc_orig: ANIM_PISTOL_JOG (fallen/Headers/animate.h)
#define ANIM_PISTOL_JOG (267)
// uc_orig: ANIM_SNIPE_AIM (fallen/Headers/animate.h)
#define ANIM_SNIPE_AIM (255)
// uc_orig: ANIM_SNIPE_FIRE (fallen/Headers/animate.h)
#define ANIM_SNIPE_FIRE (256)
// uc_orig: ANIM_SNIPE_NORM (fallen/Headers/animate.h)
#define ANIM_SNIPE_NORM (257)
// uc_orig: ANIM_TALK_ASK (fallen/Headers/animate.h)
#define ANIM_TALK_ASK (258)
// uc_orig: ANIM_TALK_TELL (fallen/Headers/animate.h)
#define ANIM_TALK_TELL (259)
// uc_orig: ANIM_TALK_LISTEN (fallen/Headers/animate.h)
#define ANIM_TALK_LISTEN (260)
// uc_orig: ANIM_DIE_KNECK (fallen/Headers/animate.h)
#define ANIM_DIE_KNECK (261)
// uc_orig: ANIM_QUICK_GET_UP (fallen/Headers/animate.h)
#define ANIM_QUICK_GET_UP (264)
// uc_orig: ANIM_PLUNGE_FORWARD (fallen/Headers/animate.h)
#define ANIM_PLUNGE_FORWARD (129)
// uc_orig: ANIM_PLUNGE_BACKWARD (fallen/Headers/animate.h)
#define ANIM_PLUNGE_BACKWARD (128)
// uc_orig: ANIM_PLUNGE_SLAM_FORWARD (fallen/Headers/animate.h)
#define ANIM_PLUNGE_SLAM_FORWARD (141)
// uc_orig: ANIM_PLUNGE_SLAM_BACKWARD (fallen/Headers/animate.h)
#define ANIM_PLUNGE_SLAM_BACKWARD (140)
// uc_orig: ANIM_KNIFE_DRAW (fallen/Headers/animate.h)
#define ANIM_KNIFE_DRAW (286)
// uc_orig: ANIM_KNIFE_FIGHT_READY (fallen/Headers/animate.h)
#define ANIM_KNIFE_FIGHT_READY (276)
// uc_orig: ANIM_KNIFE_ATTACK1 (fallen/Headers/animate.h)
#define ANIM_KNIFE_ATTACK1 (271)
// uc_orig: ANIM_KNIFE_ATTACK2 (fallen/Headers/animate.h)
#define ANIM_KNIFE_ATTACK2 (272)
// uc_orig: ANIM_KNIFE_ATTACK3 (fallen/Headers/animate.h)
#define ANIM_KNIFE_ATTACK3 (273)
// uc_orig: ANIM_KNIFE_ATTACK1_RET (fallen/Headers/animate.h)
#define ANIM_KNIFE_ATTACK1_RET (274)
// uc_orig: ANIM_KNIFE_ATTACK2_RET (fallen/Headers/animate.h)
#define ANIM_KNIFE_ATTACK2_RET (275)
// uc_orig: ANIM_PLUNGE_START (fallen/Headers/animate.h)
#define ANIM_PLUNGE_START (277)
// uc_orig: ANIM_CROUTCH_GETUP (fallen/Headers/animate.h)
#define ANIM_CROUTCH_GETUP (278)
// uc_orig: ANIM_FLYKICK_START (fallen/Headers/animate.h)
#define ANIM_FLYKICK_START (279)
// uc_orig: ANIM_FLYKICK_FALL (fallen/Headers/animate.h)
#define ANIM_FLYKICK_FALL (280)
// uc_orig: ANIM_FLYKICK_LAND (fallen/Headers/animate.h)
#define ANIM_FLYKICK_LAND (281)
// uc_orig: ANIM_ARREST_CROUTCH (fallen/Headers/animate.h)
#define ANIM_ARREST_CROUTCH (282)
// uc_orig: ANIM_ARREST_BE_CUFFED (fallen/Headers/animate.h)
#define ANIM_ARREST_BE_CUFFED (283)
// uc_orig: ANIM_ARREST_STRUGGLE (fallen/Headers/animate.h)
#define ANIM_ARREST_STRUGGLE (284)
// uc_orig: ANIM_ARREST_ROLL (fallen/Headers/animate.h)
#define ANIM_ARREST_ROLL (285)
// uc_orig: ANIM_POINT_GUN_LEFT (fallen/Headers/animate.h)
#define ANIM_POINT_GUN_LEFT (290)
// uc_orig: ANIM_POINT_GUN_RIGHT (fallen/Headers/animate.h)
#define ANIM_POINT_GUN_RIGHT (292)
// uc_orig: ANIM_POINT_SHOTGUN_LEFT (fallen/Headers/animate.h)
#define ANIM_POINT_SHOTGUN_LEFT (294)
// uc_orig: ANIM_POINT_SHOTGUN_AHEAD (fallen/Headers/animate.h)
#define ANIM_POINT_SHOTGUN_AHEAD (293)
// uc_orig: ANIM_POINT_SHOTGUN_RIGHT (fallen/Headers/animate.h)
#define ANIM_POINT_SHOTGUN_RIGHT (295)
// uc_orig: ANIM_PISTOL_DRAW (fallen/Headers/animate.h)
#define ANIM_PISTOL_DRAW (296)
// uc_orig: ANIM_PISTOL_SHOOT (fallen/Headers/animate.h)
#define ANIM_PISTOL_SHOOT (297)
// uc_orig: ANIM_PISTOL_AIM_AHEAD (fallen/Headers/animate.h)
#define ANIM_PISTOL_AIM_AHEAD (298)
// uc_orig: ANIM_SHOT_DEAD_HEAD (fallen/Headers/animate.h)
#define ANIM_SHOT_DEAD_HEAD (304)
// uc_orig: ANIM_SHOT_DEAD_CHEST (fallen/Headers/animate.h)
#define ANIM_SHOT_DEAD_CHEST (305)
// uc_orig: ANIM_SHOT_DEAD_GUT (fallen/Headers/animate.h)
#define ANIM_SHOT_DEAD_GUT (306)
// uc_orig: ANIM_SHOT_DEAD_BACK (fallen/Headers/animate.h)
#define ANIM_SHOT_DEAD_BACK (307)
// uc_orig: ANIM_SHOT_DEAD_UZI (fallen/Headers/animate.h)
#define ANIM_SHOT_DEAD_UZI (308)
// uc_orig: ANIM_PISTOL_DUCK (fallen/Headers/animate.h)
#define ANIM_PISTOL_DUCK (309)
// uc_orig: ANIM_PISTOL_DUCK_HOLD (fallen/Headers/animate.h)
#define ANIM_PISTOL_DUCK_HOLD (310)
// uc_orig: ANIM_PISTOL_STANDUP (fallen/Headers/animate.h)
#define ANIM_PISTOL_STANDUP (311)
// uc_orig: ANIM_SHOTGUN_DUCK (fallen/Headers/animate.h)
#define ANIM_SHOTGUN_DUCK (312)
// uc_orig: ANIM_SHOTGUN_DUCK_HOLD (fallen/Headers/animate.h)
#define ANIM_SHOTGUN_DUCK_HOLD (313)
// uc_orig: ANIM_SHOTGUN_STANDUP (fallen/Headers/animate.h)
#define ANIM_SHOTGUN_STANDUP (314)
// uc_orig: ANIM_SNIPER_CRAWL (fallen/Headers/animate.h)
#define ANIM_SNIPER_CRAWL (315)
// uc_orig: ANIM_HIT_WALL (fallen/Headers/animate.h)
#define ANIM_HIT_WALL (316)
// uc_orig: ANIM_DIVE_LEFT (fallen/Headers/animate.h)
#define ANIM_DIVE_LEFT (317)
// uc_orig: ANIM_DIVE_RIGHT (fallen/Headers/animate.h)
#define ANIM_DIVE_RIGHT (318)
// uc_orig: ANIM_YOMP_START_AK (fallen/Headers/animate.h)
#define ANIM_YOMP_START_AK (321)
// uc_orig: ANIM_PRESS_WALL_TURN (fallen/Headers/animate.h)
#define ANIM_PRESS_WALL_TURN (322)
// uc_orig: ANIM_PRESS_WALL_STAND (fallen/Headers/animate.h)
#define ANIM_PRESS_WALL_STAND (323)
// uc_orig: ANIM_PRESS_WALL_SIDLE_L (fallen/Headers/animate.h)
#define ANIM_PRESS_WALL_SIDLE_L (324)
// uc_orig: ANIM_PRESS_WALL_SIDLE_R (fallen/Headers/animate.h)
#define ANIM_PRESS_WALL_SIDLE_R (325)
// uc_orig: ANIM_PRESS_WALL_TURN_AK (fallen/Headers/animate.h)
#define ANIM_PRESS_WALL_TURN_AK (326)
// uc_orig: ANIM_PRESS_WALL_STAND_AK (fallen/Headers/animate.h)
#define ANIM_PRESS_WALL_STAND_AK (327)
// uc_orig: ANIM_PRESS_WALL_SIDLE_L_AK (fallen/Headers/animate.h)
#define ANIM_PRESS_WALL_SIDLE_L_AK (328)
// uc_orig: ANIM_PRESS_WALL_SIDLE_R_AK (fallen/Headers/animate.h)
#define ANIM_PRESS_WALL_SIDLE_R_AK (329)
// uc_orig: ANIM_GET_UP_HALF_BLOCK (fallen/Headers/animate.h)
#define ANIM_GET_UP_HALF_BLOCK (330)
// uc_orig: ANIM_PULL_UP_NEW (fallen/Headers/animate.h)
#define ANIM_PULL_UP_NEW (332)
// uc_orig: ANIM_SURF (fallen/Headers/animate.h)
#define ANIM_SURF (333)
// uc_orig: ANIM_SURF_AK (fallen/Headers/animate.h)
#define ANIM_SURF_AK (335)
// uc_orig: ANIM_BACK_WALK (fallen/Headers/animate.h)
#define ANIM_BACK_WALK (334)
// uc_orig: ANIM_BACK_WALK_AK (fallen/Headers/animate.h)
#define ANIM_BACK_WALK_AK (336)
// uc_orig: ANIM_SIT_DOWN (fallen/Headers/animate.h)
#define ANIM_SIT_DOWN (337)
// uc_orig: ANIM_SIT_IDLE (fallen/Headers/animate.h)
#define ANIM_SIT_IDLE (338)
// uc_orig: ANIM_SIT_TO_STAND (fallen/Headers/animate.h)
#define ANIM_SIT_TO_STAND (339)
// uc_orig: ANIM_STOP_RUN (fallen/Headers/animate.h)
#define ANIM_STOP_RUN (340)
// uc_orig: ANIM_PRESS_WALL_TURN_PISTOL (fallen/Headers/animate.h)
#define ANIM_PRESS_WALL_TURN_PISTOL (341)
// uc_orig: ANIM_PRESS_WALL_STAND_PISTOL (fallen/Headers/animate.h)
#define ANIM_PRESS_WALL_STAND_PISTOL (342)
// uc_orig: ANIM_PRESS_WALL_SIDLE_L_PISTOL (fallen/Headers/animate.h)
#define ANIM_PRESS_WALL_SIDLE_L_PISTOL (343)
// uc_orig: ANIM_PRESS_WALL_SIDLE_R_PISTOL (fallen/Headers/animate.h)
#define ANIM_PRESS_WALL_SIDLE_R_PISTOL (344)
// uc_orig: ANIM_PRESS_WALL_LOOK_L_PISTOL (fallen/Headers/animate.h)
#define ANIM_PRESS_WALL_LOOK_L_PISTOL (345)
// uc_orig: ANIM_PRESS_WALL_LOOK_R_PISTOL (fallen/Headers/animate.h)
#define ANIM_PRESS_WALL_LOOK_R_PISTOL (346)
// uc_orig: ANIM_PRESS_WALL_LOOK_L_AK (fallen/Headers/animate.h)
#define ANIM_PRESS_WALL_LOOK_L_AK (347)
// uc_orig: ANIM_PRESS_WALL_LOOK_R_AK (fallen/Headers/animate.h)
#define ANIM_PRESS_WALL_LOOK_R_AK (348)
// uc_orig: ANIM_PRESS_WALL_LOOK_L (fallen/Headers/animate.h)
#define ANIM_PRESS_WALL_LOOK_L (349)
// uc_orig: ANIM_PRESS_WALL_LOOK_R (fallen/Headers/animate.h)
#define ANIM_PRESS_WALL_LOOK_R (350)
// uc_orig: ANIM_PRESS_WALL_FREEZE_L_PISTOL (fallen/Headers/animate.h)
#define ANIM_PRESS_WALL_FREEZE_L_PISTOL (351)
// uc_orig: ANIM_PRESS_WALL_FREEZE_R_PISTOL (fallen/Headers/animate.h)
#define ANIM_PRESS_WALL_FREEZE_R_PISTOL (352)
// uc_orig: ANIM_PRESS_WALL_FREEZE_L_AK (fallen/Headers/animate.h)
#define ANIM_PRESS_WALL_FREEZE_L_AK (353)
// uc_orig: ANIM_PRESS_WALL_FREEZE_R_AK (fallen/Headers/animate.h)
#define ANIM_PRESS_WALL_FREEZE_R_AK (354)
// uc_orig: ANIM_PRESS_WALL_FREEZE_L (fallen/Headers/animate.h)
#define ANIM_PRESS_WALL_FREEZE_L (355)
// uc_orig: ANIM_PRESS_WALL_FREEZE_R (fallen/Headers/animate.h)
#define ANIM_PRESS_WALL_FREEZE_R (356)
// uc_orig: ANIM_UNFIGHT (fallen/Headers/animate.h)
#define ANIM_UNFIGHT (358)
// uc_orig: ANIM_BIKE_DISMOUNT (fallen/Headers/animate.h)
#define ANIM_BIKE_DISMOUNT (360)
// uc_orig: ANIM_BIKE_FALL_OVER_BARS (fallen/Headers/animate.h)
#define ANIM_BIKE_FALL_OVER_BARS (361)
// uc_orig: ANIM_FIGHT_STEP_N_BAT (fallen/Headers/animate.h)
#define ANIM_FIGHT_STEP_N_BAT (375)
// uc_orig: ANIM_FIGHT_STEP_S_BAT (fallen/Headers/animate.h)
#define ANIM_FIGHT_STEP_S_BAT (376)
// uc_orig: ANIM_FIGHT_STEP_E_BAT (fallen/Headers/animate.h)
#define ANIM_FIGHT_STEP_E_BAT (377)
// uc_orig: ANIM_FIGHT_STEP_W_BAT (fallen/Headers/animate.h)
#define ANIM_FIGHT_STEP_W_BAT (378)
// uc_orig: ANIM_FIGHT_SHUFFLE_BAT (fallen/Headers/animate.h)
#define ANIM_FIGHT_SHUFFLE_BAT (379)
// uc_orig: ANIM_YOMP_START_PISTOL (fallen/Headers/animate.h)
#define ANIM_YOMP_START_PISTOL (368)
// uc_orig: ANIM_YOMP_START_BAT (fallen/Headers/animate.h)
#define ANIM_YOMP_START_BAT (371)
// uc_orig: ANIM_YOMP_BAT (fallen/Headers/animate.h)
#define ANIM_YOMP_BAT (370)
// uc_orig: ANIM_SHOTGUN_IDLE (fallen/Headers/animate.h)
#define ANIM_SHOTGUN_IDLE (383)
// uc_orig: ANIM_THUG_WALK_SHOTGUN (fallen/Headers/animate.h)
#define ANIM_THUG_WALK_SHOTGUN (384)
// uc_orig: ANIM_THUG_WALK (fallen/Headers/animate.h)
#define ANIM_THUG_WALK (389)
// uc_orig: ANIM_INJURED_LOOP (fallen/Headers/animate.h)
#define ANIM_INJURED_LOOP (386)
// uc_orig: ANIM_INJURED_LOOP_STRUGGLE (fallen/Headers/animate.h)
#define ANIM_INJURED_LOOP_STRUGGLE (387)
// uc_orig: ANIM_BIGLAND_DIE (fallen/Headers/animate.h)
#define ANIM_BIGLAND_DIE (388)
// uc_orig: ANIM_UNCROUTCH_PISTOL (fallen/Headers/animate.h)
#define ANIM_UNCROUTCH_PISTOL (311)
// uc_orig: ANIM_UNCROUTCH_AK (fallen/Headers/animate.h)
#define ANIM_UNCROUTCH_AK (314)
// uc_orig: ANIM_PISTOL_WHIP (fallen/Headers/animate.h)
#define ANIM_PISTOL_WHIP (391)
// uc_orig: ANIM_PISTOL_WHIP_TAKE (fallen/Headers/animate.h)
#define ANIM_PISTOL_WHIP_TAKE (392)
// uc_orig: ANIM_KICK_NAD (fallen/Headers/animate.h)
#define ANIM_KICK_NAD (394)
// uc_orig: ANIM_KICK_NAD_TAKE (fallen/Headers/animate.h)
#define ANIM_KICK_NAD_TAKE (395)
// uc_orig: ANIM_KICK_NAD_STUNNED (fallen/Headers/animate.h)
#define ANIM_KICK_NAD_STUNNED (396)
// uc_orig: ANIM_KICK_NAD_RECOVER (fallen/Headers/animate.h)
#define ANIM_KICK_NAD_RECOVER (397)
// uc_orig: ANIM_VALVE_LOOP (fallen/Headers/animate.h)
#define ANIM_VALVE_LOOP (398)
// uc_orig: ANIM_VALVE_END (fallen/Headers/animate.h)
#define ANIM_VALVE_END (399)
// uc_orig: ANIM_END (fallen/Headers/animate.h)
// Base value for Darci's "borrowed" clips from other character sets (ANIM_END+N).
#define ANIM_END (400)

// Darci borrows clips from other character rigs at runtime (ANIM_END+N).
// uc_orig: ANIM_EXIT_VAN (fallen/Headers/animate.h)
#define ANIM_EXIT_VAN (ANIM_END + 1)
// uc_orig: ANIM_ENTER_VAN (fallen/Headers/animate.h)
#define ANIM_ENTER_VAN (ANIM_END + 2)
// uc_orig: ANIM_WANKER (fallen/Headers/animate.h)
#define ANIM_WANKER (ANIM_END + 3)
// uc_orig: ANIM_RUN_TAXI (fallen/Headers/animate.h)
#define ANIM_RUN_TAXI (ANIM_END + 4)
// uc_orig: ANIM_RUN_FLEE (fallen/Headers/animate.h)
#define ANIM_RUN_FLEE (ANIM_END + 5)
// uc_orig: ANIM_HAIL_TAXI (fallen/Headers/animate.h)
#define ANIM_HAIL_TAXI (ANIM_END + 6)
// uc_orig: ANIM_ENTER_TAXI (fallen/Headers/animate.h)
#define ANIM_ENTER_TAXI (ANIM_END + 7)
// uc_orig: ANIM_PUTDOWN_CARRY_V (fallen/Headers/animate.h)
#define ANIM_PUTDOWN_CARRY_V (ANIM_END + 8)
// uc_orig: ANIM_STAND_CARRY (fallen/Headers/animate.h)
#define ANIM_STAND_CARRY (ANIM_END + 9)
// uc_orig: ANIM_STAND_CARRY_V (fallen/Headers/animate.h)
#define ANIM_STAND_CARRY_V (ANIM_END + 10)
// uc_orig: ANIM_IDLE_BREATH (fallen/Headers/animate.h)
#define ANIM_IDLE_BREATH (ANIM_END + 11)
// uc_orig: ANIM_IDLE_PHONE_ANSWER (fallen/Headers/animate.h)
#define ANIM_IDLE_PHONE_ANSWER (ANIM_END + 12)
// uc_orig: ANIM_IDLE_PHONE_TALK (fallen/Headers/animate.h)
#define ANIM_IDLE_PHONE_TALK (ANIM_END + 13)
// uc_orig: ANIM_FIGHT_STANCE_WIMP (fallen/Headers/animate.h)
#define ANIM_FIGHT_STANCE_WIMP (ANIM_END + 14)
// uc_orig: ANIM_FIGHT_STANCE_HARD (fallen/Headers/animate.h)
#define ANIM_FIGHT_STANCE_HARD (ANIM_END + 15)
// uc_orig: ANIM_DANCE_BOOGIE (fallen/Headers/animate.h)
#define ANIM_DANCE_BOOGIE (ANIM_END + 16)
// uc_orig: ANIM_DANCE_WOOGIE (fallen/Headers/animate.h)
#define ANIM_DANCE_WOOGIE (ANIM_END + 17)
// uc_orig: ANIM_DANCE_HEADBANG (fallen/Headers/animate.h)
#define ANIM_DANCE_HEADBANG (ANIM_END + 18)
// uc_orig: ANIM_WARM_HANDS (fallen/Headers/animate.h)
#define ANIM_WARM_HANDS (ANIM_END + 19)
// uc_orig: ANIM_HANDS_UP (fallen/Headers/animate.h)
#define ANIM_HANDS_UP (ANIM_END + 20)
// uc_orig: ANIM_STRANGLE (fallen/Headers/animate.h)
#define ANIM_STRANGLE (ANIM_END + 21)
// uc_orig: ANIM_STRANGLE_VICTIM (fallen/Headers/animate.h)
#define ANIM_STRANGLE_VICTIM (ANIM_END + 22)
// uc_orig: ANIM_HEADBUTT (fallen/Headers/animate.h)
#define ANIM_HEADBUTT (ANIM_END + 23)
// uc_orig: ANIM_HEADBUTT_VICTIM (fallen/Headers/animate.h)
#define ANIM_HEADBUTT_VICTIM (ANIM_END + 24)
// uc_orig: ANIM_HANDS_UP_LOOP (fallen/Headers/animate.h)
#define ANIM_HANDS_UP_LOOP (ANIM_END + 26)
// uc_orig: ANIM_PICKUP_CARRY (fallen/Headers/animate.h)
#define ANIM_PICKUP_CARRY (ANIM_END + 27)
// uc_orig: ANIM_START_WALK_CARRY (fallen/Headers/animate.h)
#define ANIM_START_WALK_CARRY (ANIM_END + 28)
// uc_orig: ANIM_WALK_CARRY (fallen/Headers/animate.h)
#define ANIM_WALK_CARRY (ANIM_END + 29)
// uc_orig: ANIM_WALK_STOP_CARRY (fallen/Headers/animate.h)
#define ANIM_WALK_STOP_CARRY (ANIM_END + 30)
// uc_orig: ANIM_PUTDOWN_CARRY (fallen/Headers/animate.h)
#define ANIM_PUTDOWN_CARRY (ANIM_END + 31)
// uc_orig: ANIM_PICKUP_CARRY_V (fallen/Headers/animate.h)
#define ANIM_PICKUP_CARRY_V (ANIM_END + 32)
// uc_orig: ANIM_START_WALK_CARRY_V (fallen/Headers/animate.h)
#define ANIM_START_WALK_CARRY_V (ANIM_END + 33)
// uc_orig: ANIM_WALK_CARRY_V (fallen/Headers/animate.h)
#define ANIM_WALK_CARRY_V (ANIM_END + 34)
// uc_orig: ANIM_WALK_STOP_CARRY_V (fallen/Headers/animate.h)
#define ANIM_WALK_STOP_CARRY_V (ANIM_END + 35)
// uc_orig: ANIM_HANDS_UP_LIE (fallen/Headers/animate.h)
#define ANIM_HANDS_UP_LIE (ANIM_END + 36)

// --------------------------------------------------------------------------
// Per-frame action states (Person.Action field)
// --------------------------------------------------------------------------

// uc_orig: ACTION_IDLE (fallen/Headers/animate.h)
#define ACTION_IDLE (0)
// uc_orig: ACTION_WALK (fallen/Headers/animate.h)
#define ACTION_WALK (1)
// uc_orig: ACTION_RUN (fallen/Headers/animate.h)
#define ACTION_RUN (2)
// uc_orig: ACTION_STANDING_JUMP (fallen/Headers/animate.h)
#define ACTION_STANDING_JUMP (3)
// uc_orig: ACTION_STANDING_JUMP_GRAB (fallen/Headers/animate.h)
#define ACTION_STANDING_JUMP_GRAB (4)
// uc_orig: ACTION_RUNNING_JUMP (fallen/Headers/animate.h)
#define ACTION_RUNNING_JUMP (5)
// uc_orig: ACTION_DANGLING (fallen/Headers/animate.h)
#define ACTION_DANGLING (6)
// uc_orig: ACTION_PULL_UP (fallen/Headers/animate.h)
#define ACTION_PULL_UP (7)
// uc_orig: ACTION_STAND_RELAX (fallen/Headers/animate.h)
#define ACTION_STAND_RELAX (8)
// uc_orig: ACTION_GRABBING_LEDGE (fallen/Headers/animate.h)
#define ACTION_GRABBING_LEDGE (9)
// uc_orig: ACTION_NONE (fallen/Headers/animate.h)
#define ACTION_NONE (10)
// uc_orig: ACTION_DROP_DOWN (fallen/Headers/animate.h)
#define ACTION_DROP_DOWN (10)
// uc_orig: ACTION_FALLING (fallen/Headers/animate.h)
#define ACTION_FALLING (11)
// uc_orig: ACTION_LANDING (fallen/Headers/animate.h)
#define ACTION_LANDING (12)
// uc_orig: ACTION_CLIMBING (fallen/Headers/animate.h)
#define ACTION_CLIMBING (13)
// uc_orig: ACTION_FIGHT_PUNCH (fallen/Headers/animate.h)
#define ACTION_FIGHT_PUNCH (14)
// uc_orig: ACTION_FIGHT_KICK (fallen/Headers/animate.h)
#define ACTION_FIGHT_KICK (15)
// uc_orig: ACTION_FIGHT_IDLE (fallen/Headers/animate.h)
#define ACTION_FIGHT_IDLE (16)
// uc_orig: ACTION_DANGLING_CABLE (fallen/Headers/animate.h)
#define ACTION_DANGLING_CABLE (17)
// uc_orig: ACTION_HOP_BACK (fallen/Headers/animate.h)
#define ACTION_HOP_BACK (18)
// uc_orig: ACTION_SIDE_STEP (fallen/Headers/animate.h)
#define ACTION_SIDE_STEP (19)
// uc_orig: ACTION_DYING (fallen/Headers/animate.h)
#define ACTION_DYING (20)
// uc_orig: ACTION_DRAW_SPECIAL (fallen/Headers/animate.h)
#define ACTION_DRAW_SPECIAL (21)
// uc_orig: ACTION_AIM_GUN (fallen/Headers/animate.h)
#define ACTION_AIM_GUN (22)
// uc_orig: ACTION_SHOOT (fallen/Headers/animate.h)
#define ACTION_SHOOT (23)
// uc_orig: ACTION_GUN_AWAY (fallen/Headers/animate.h)
#define ACTION_GUN_AWAY (24)
// uc_orig: ACTION_RESPAWN (fallen/Headers/animate.h)
#define ACTION_RESPAWN (25)
// uc_orig: ACTION_DEAD (fallen/Headers/animate.h)
#define ACTION_DEAD (26)
// uc_orig: ACTION_FLIP_LEFT (fallen/Headers/animate.h)
#define ACTION_FLIP_LEFT (27)
// uc_orig: ACTION_FLIP_RIGHT (fallen/Headers/animate.h)
#define ACTION_FLIP_RIGHT (28)
// uc_orig: ACTION_STOPPING (fallen/Headers/animate.h)
#define ACTION_STOPPING (30)
// uc_orig: ACTION_RUN_JUMP (fallen/Headers/animate.h)
#define ACTION_RUN_JUMP (31)
// uc_orig: ACTION_KICK_FLAG (fallen/Headers/animate.h)
#define ACTION_KICK_FLAG (32)
// uc_orig: ACTION_JUMP_FLAG (fallen/Headers/animate.h)
#define ACTION_JUMP_FLAG (33)
// uc_orig: ACTION_WALK_BACK (fallen/Headers/animate.h)
#define ACTION_WALK_BACK (34)
// uc_orig: ACTION_DEATH_SLIDE (fallen/Headers/animate.h)
#define ACTION_DEATH_SLIDE (35)
// uc_orig: ACTION_TRAVERSE_LEFT (fallen/Headers/animate.h)
#define ACTION_TRAVERSE_LEFT (36)
// uc_orig: ACTION_TRAVERSE_RIGHT (fallen/Headers/animate.h)
#define ACTION_TRAVERSE_RIGHT (37)
// uc_orig: ACTION_PUNCH_FLAG (fallen/Headers/animate.h)
#define ACTION_PUNCH_FLAG (38)
// uc_orig: ACTION_BLOCK_FLAG (fallen/Headers/animate.h)
#define ACTION_BLOCK_FLAG (39)
// uc_orig: ACTION_CROUTCH (fallen/Headers/animate.h)
#define ACTION_CROUTCH (40)
// uc_orig: ACTION_CRAWLING (fallen/Headers/animate.h)
#define ACTION_CRAWLING (41)
// uc_orig: ACTION_SKID (fallen/Headers/animate.h)
#define ACTION_SKID (42)
// uc_orig: ACTION_GRAPPLE (fallen/Headers/animate.h)
#define ACTION_GRAPPLE (43)
// uc_orig: ACTION_GRAPPLEE (fallen/Headers/animate.h)
#define ACTION_GRAPPLEE (44)
// uc_orig: ACTION_ENTER_VEHICLE (fallen/Headers/animate.h)
#define ACTION_ENTER_VEHICLE (45)
// uc_orig: ACTION_INSIDE_VEHICLE (fallen/Headers/animate.h)
#define ACTION_INSIDE_VEHICLE (46)
// uc_orig: ACTION_SIT_BENCH (fallen/Headers/animate.h)
#define ACTION_SIT_BENCH (47)
// uc_orig: ACTION_HUG_WALL (fallen/Headers/animate.h)
#define ACTION_HUG_WALL (48)
// uc_orig: ACTION_HUG_LEFT (fallen/Headers/animate.h)
#define ACTION_HUG_LEFT (49)
// uc_orig: ACTION_HUG_RIGHT (fallen/Headers/animate.h)
#define ACTION_HUG_RIGHT (50)
// uc_orig: ACTION_UNSIT (fallen/Headers/animate.h)
#define ACTION_UNSIT (51)

// --------------------------------------------------------------------------
// Skeleton body part indices (used with sub-object/bone lookup)
// --------------------------------------------------------------------------

// uc_orig: SUB_OBJECT_PELVIS (fallen/Headers/animate.h)
#define SUB_OBJECT_PELVIS (0)
// uc_orig: SUB_OBJECT_LEFT_FEMUR (fallen/Headers/animate.h)
#define SUB_OBJECT_LEFT_FEMUR (1)
// uc_orig: SUB_OBJECT_LEFT_TIBIA (fallen/Headers/animate.h)
#define SUB_OBJECT_LEFT_TIBIA (2)
// uc_orig: SUB_OBJECT_LEFT_FOOT (fallen/Headers/animate.h)
#define SUB_OBJECT_LEFT_FOOT (3)
// uc_orig: SUB_OBJECT_TORSO (fallen/Headers/animate.h)
#define SUB_OBJECT_TORSO (4)
// uc_orig: SUB_OBJECT_LEFT_HUMORUS (fallen/Headers/animate.h)
#define SUB_OBJECT_LEFT_HUMORUS (5)
// uc_orig: SUB_OBJECT_LEFT_RADIUS (fallen/Headers/animate.h)
#define SUB_OBJECT_LEFT_RADIUS (6)
// uc_orig: SUB_OBJECT_LEFT_HAND (fallen/Headers/animate.h)
#define SUB_OBJECT_LEFT_HAND (7)
// uc_orig: SUB_OBJECT_RIGHT_HUMORUS (fallen/Headers/animate.h)
#define SUB_OBJECT_RIGHT_HUMORUS (8)
// uc_orig: SUB_OBJECT_RIGHT_RADIUS (fallen/Headers/animate.h)
#define SUB_OBJECT_RIGHT_RADIUS (9)
// uc_orig: SUB_OBJECT_RIGHT_HAND (fallen/Headers/animate.h)
#define SUB_OBJECT_RIGHT_HAND (10)
// uc_orig: SUB_OBJECT_HEAD (fallen/Headers/animate.h)
#define SUB_OBJECT_HEAD (11)
// uc_orig: SUB_OBJECT_RIGHT_FEMUR (fallen/Headers/animate.h)
#define SUB_OBJECT_RIGHT_FEMUR (12)
// uc_orig: SUB_OBJECT_RIGHT_TIBIA (fallen/Headers/animate.h)
#define SUB_OBJECT_RIGHT_TIBIA (13)
// uc_orig: SUB_OBJECT_RIGHT_FOOT (fallen/Headers/animate.h)
#define SUB_OBJECT_RIGHT_FOOT (14)
// uc_orig: SUB_OBJECT_PREFERRED_HAND (fallen/Headers/animate.h)
// Sentinel value: use the character's dominant hand at runtime.
#define SUB_OBJECT_PREFERRED_HAND (65535)

#endif // ACTORS_CHARACTERS_ANIM_IDS_H
