// PlayStation help bodies. Edit freely. Inline glyph tokens use ps_* ids from
// input_prompt_map. Shared device-agnostic prose lives in help_content_common.h.
// (REFERENCE, MOVEMENT and COMBAT are written; WEAPONS is still a placeholder.)

#include "ui/menus/help_content_bodies.h"
#include "ui/menus/help_content_common.h"

// Section 1 — full button reference (the "control map"). One line per unique
// control, listing every gameplay situation it is used in (on foot + in a car).
const char* const HELP_CONTROLS_PS =
    HELP_TXT_CONTROLS_INTRO "\n"
    "\n"
    "{ps_rs} - Look around.\n"
    "{ps_r2} - Attack or shoot. In a car: gas.\n"
    "{ps_r1} - Kick.\n"
    "{ps_r3} - Draw or holster your weapon.\n"
    "{ps_r3}+{ps_dpad_up} / {ps_r3}+{ps_dpad_down} - Cycle through "
    "your weapons.\n"
    "{ps_ls} - Move and run. In a car: steering.\n"
    "{ps_cross} - Jump.\n"
    "{ps_circle} - Sprint.\n"
    "{ps_l2} - Slow walk and rolls. In a car: reverse.\n"
    "{ps_square} - Action: get in or out of a car, pick up items, search "
    "bodies, arrest, and interact with the world. Switch target in a fight.\n"
    "{ps_triangle} - Stealth. In a car: siren.\n"
    "{ps_l1} - Zoom in to look around; back-step while moving. In a car: brake.\n"
    "{ps_dpad_up} - Select weapon: pistol.\n"
    "{ps_dpad_left} - Select weapon: M16.\n"
    "{ps_dpad_right} - Select weapon: shotgun.\n"
    "{ps_dpad_up}+{ps_dpad_right} - Select weapon: grenade.\n"
    "{ps_dpad_down} - Switch melee weapon: bat or knife.\n"
    "{ps_start} - Pause.";

const char* const HELP_MOVEMENT_PS =
    "MOVING\n"
    "Run with the {ps_ls}; hold {ps_circle} while running to sprint.\n"
    "Hold {ps_l2} to walk slowly and quietly.\n"
    "Hold {ps_l1} and push back to walk backwards while still facing front; "
    "pushing forward is ignored.\n"
    "\n"
    "CAMERA\n"
    "Move the {ps_rs} to swing the camera; Darci always turns to face where it "
    "points, so you can also steer where she runs by swinging the camera as she "
    "goes. From a standstill, hold {ps_l1} to zoom in for a closer look.\n"
    "\n"
    "JUMPING\n"
    "Tap {ps_cross} to jump, on the spot or along your run. Jump while backing "
    "away to do a backflip.\n"
    "\n"
    "CLIMBING\n"
    "Jump at a ledge to grab on if you reach it; tap {ps_cross} again to climb "
    "up, or edge left and right while hanging.\n"
    "Walk into a ladder to grab on; to get on heading down, back up to it (hold "
    "{ps_l1} and push back) and press {ps_square}. Once on, push forward or back "
    "to climb up or down.\n"
    "Jump onto a wire, often strung between buildings, and Darci catches it and "
    "slides down.\n"
    "\n"
    "ROLLING\n"
    "While moving, tap {ps_l2} with a direction to roll that way.\n"
    "\n"
    "STEALTH\n"
    "From a standstill, hold {ps_triangle} to crouch; then move to crawl on all "
    "fours and stay out of sight.\n"
    "\n"
    "WALL HUG\n"
    "Press {ps_square} against a wall to flatten against it and edge along, left "
    "or right.";

const char* const HELP_COMBAT_PS =
    "FIGHTING STANCE\n"
    "Darci drops into a fighting stance by herself whenever a close fight "
    "starts. In it she stays focused on one enemy - switch target with "
    "{ps_square}. You can't just run out of a fight: roll to break away - any "
    "roll cancels the stance, and in a fight you can roll with {ps_l2} or "
    "{ps_cross} as long as you hold a direction.\n"
    "\n"
    "STRIKES AND COMBOS\n"
    "Attack with {ps_r2} (hands) or {ps_r1} (feet). Press them a few times, or "
    "alternate the two, to chain a combo - if a follow-up does not come out, "
    "that is normal, the extra hits are not guaranteed. In the stance, hold a "
    "direction with {ps_r1} to kick that way. A bat or knife attacks with "
    "{ps_r2}, and you can still kick.\n"
    "\n"
    "GRAPPLE\n"
    "Press {ps_r2} while moving into an enemy right in front of you to grab "
    "them. From the hold, {ps_r2} tries to throw them down (it can fail and "
    "just shove them away), or {ps_r1} knees them, up to twice if you are "
    "quick. Darci then lets go.\n"
    "\n"
    "DODGE\n"
    "Push back as an enemy attacks and Darci ducks under the blow; hold to stay "
    "low (she stands after a moment). Kick while ducking to sweep nearby enemies "
    "off their feet.\n"
    "\n"
    "RUNNING MOVES\n"
    "Press {ps_r1} while running for a sliding kick that knocks down anyone you "
    "slide into. Jump while running and press {ps_r1} in the air for a flying "
    "kick.\n"
    "\n"
    "DOWNED ENEMIES\n"
    "Stand over an enemy you have knocked down, while they are still alive, and "
    "press {ps_square} to arrest them. Facing a downed enemy up close, press "
    "{ps_r1} to stomp them.";

const char* const HELP_WEAPONS_PS =
    "Pick up weapons found in the level. Press {ps_r2} to fire the held weapon.";
