// Keyboard & mouse help bodies. Edit freely. Inline glyph tokens use kb_* / ms_*
// ids from input_prompt_map. Shared device-agnostic prose lives in
// help_content_common.h. (All topics written: CONTROLS, MOVEMENT, COMBAT,
// WEAPONS, DRIVING, OTHER.)

#include "ui/menus/help_content_bodies.h"
#include "ui/menus/help_content_common.h"

// Section 1 — full button reference (the "control map"). One line per unique
// control, listing every gameplay situation it is used in (on foot + in a car).
// Short reference, not a how-to; the per-mechanic guide topics cover usage.
const char* const HELP_CONTROLS_KBM =
    HELP_TXT_CONTROLS_INTRO "\n"
    "\n"
    "GENERAL\n"
    "{ms_move} - Look around - rotates the camera.\n"
    "{kb_esc} - Pause.\n"
    "\n"
    "ON FOOT\n"
    "{ms_lmb} - Attack or shoot.\n"
    "{ms_rmb} - Kick.\n"
    "{kb_w}{kb_a}{kb_s}{kb_d} - Move and run.\n"
    "{kb_space} - Jump.\n"
    "{kb_shift} - Sprint.\n"
    "{kb_ctrl} - Slow walk and rolls.\n"
    "{kb_f} - Action: get into a car, pick up items, search bodies, arrest, and "
    "interact with the world. Switch target in a fight.\n"
    "{kb_c} - Stealth.\n"
    "{kb_e} - Zoom in to look around; back-step while moving.\n"
    "\n"
    "CHANGING WEAPONS\n"
    "{ms_mmb} - Switch to the next weapon.\n"
    "{ms_wheel} - Cycle through your weapons.\n"
    "{kb_1} - Pistol.\n"
    "{kb_2} - M16.\n"
    "{kb_3} - Shotgun.\n"
    "{kb_4} - Grenade.\n"
    "{kb_backtick} - Put a drawn gun away, or switch melee: fists, bat, knife.\n"
    "\n"
    "IN A CAR\n"
    "{kb_w} - Accelerate.\n"
    "{kb_s} - Reverse.\n"
    "{kb_a}{kb_d} - Steering.\n"
    "{kb_space} - Brake.\n"
    "{kb_e} - Siren.\n"
    "{kb_f} - Get out of the car."
    ;

const char* const HELP_MOVEMENT_KBM =
    "MOVING\n"
    "Run with {kb_w}{kb_a}{kb_s}{kb_d}; hold {kb_shift} while running to "
    "sprint.\n"
    "Hold {kb_ctrl} to walk slowly and quietly.\n"
    "Hold {kb_e} and push back to walk backwards while still facing front; "
    "pushing forward is ignored.\n"
    "\n"
    "CAMERA\n"
    "Move {ms_move} to rotate the camera. Movement is camera-relative: Darci "
    "runs in the direction you push relative to the camera, so swinging the "
    "camera steers her as she goes. From a standstill, hold {kb_e} to zoom in "
    "for a closer look.\n"
    "\n"
    "JUMPING\n"
    "Tap {kb_space} to jump, on the spot or along your run. Jump while backing "
    "away to do a backflip.\n"
    "\n"
    "CLIMBING\n"
    "Jump at a ledge to grab on if you reach it; tap {kb_space} again to climb "
    "up, or edge left and right while hanging.\n"
    "To climb up, just walk into a ladder. To climb down, walk up to it and "
    "press {kb_f}. Once on, push forward or back to go up or down.\n"
    "Jump onto a wire, often strung between buildings, and Darci catches it and "
    "slides down.\n"
    "\n"
    "ROLLING\n"
    "While moving, tap {kb_ctrl} with a direction to roll that way.\n"
    "\n"
    "STEALTH\n"
    "From a standstill, hold {kb_c} to crouch; then move to crawl on all fours "
    "and stay out of sight.\n"
    "\n"
    "WALL HUG\n"
    "Press {kb_f} against a wall to flatten against it and edge along, left or "
    "right.";

const char* const HELP_COMBAT_KBM =
    "FIGHTING STANCE\n"
    "Darci drops into a fighting stance by herself whenever a close fight "
    "starts. In it she stays focused on one enemy - switch target with {kb_f}. "
    "You can't just run out of a fight: roll to break away - any roll drops the "
    "stance, and in a fight you can roll with {kb_ctrl} or {kb_space} as long as "
    "you hold a direction. Drawing a gun mid-fight also drops the stance (a bat "
    "or knife does not).\n"
    "\n"
    "STRIKES AND COMBOS\n"
    "Attack with {ms_lmb} (hands) or {ms_rmb} (feet). Press them a few times, or "
    "alternate the two, to chain a combo - if a follow-up does not come out, "
    "that is normal, the extra hits are not guaranteed. In the stance, hold a "
    "direction with {ms_rmb} to kick that way. A bat or knife attacks with "
    "{ms_lmb}, and you can still kick.\n"
    "\n"
    "GRAPPLE\n"
    "Press {ms_lmb} while moving into an enemy right in front of you to grab "
    "them. From the hold, {ms_lmb} tries to throw them down (it can fail and "
    "just shove them away), or {ms_rmb} knees them, up to twice if you are "
    "quick. Darci then lets go.\n"
    "\n"
    "DODGE\n"
    "Push back as an enemy attacks and Darci ducks under the blow; hold to stay "
    "low (she stands after a moment). Kick while ducking to sweep nearby enemies "
    "off their feet.\n"
    "\n"
    "RUNNING MOVES\n"
    "Press {ms_rmb} while running for a sliding kick that knocks down anyone you "
    "slide into. Jump while running and press {ms_rmb} in the air for a flying "
    "kick.\n"
    "\n"
    "DOWNED ENEMIES\n"
    "Stand over an enemy you have knocked down, while they are still alive, and "
    "press {kb_f} to arrest them. Facing a downed enemy up close, press {ms_rmb} "
    "to stomp them.";

const char* const HELP_WEAPONS_KBM =
    "SHOOTING\n"
    "With a gun out, fire with {ms_lmb}. Darci shoots wherever she is facing; she "
    "locks onto people and certain objects near her line of sight so the shot "
    "connects. You can fire on the move as well as standing still. {ms_lmb} "
    "fires "
    "one shot from the pistol or shotgun; hold it with the M16 for automatic "
    "fire.\n"
    "\n"
    "RELOADING AND AMMO\n"
    "When a gun runs dry the next {ms_lmb} reloads a spare magazine instead of "
    "firing - press again to shoot. When a weapon is completely out, Darci "
    "switches to your best remaining weapon with ammo, or to bare hands if "
    "nothing is left. Spare ammo and dropped guns are picked up automatically as "
    "you walk over them.\n"
    "\n"
    "GRENADE\n"
    "With the grenade selected, dotted lines show where it will land. Press "
    "{ms_lmb} once to pull the pin - a countdown appears by the grenade icon - "
    "and {ms_lmb} again to throw it. It goes off when the timer reaches zero, "
    "wherever it is - with the right timing you can make it burst in mid-air.\n"
    "\n"
    "DRAWING AND SWITCHING\n"
    "Pick a gun directly with {kb_1} (pistol), {kb_2} (M16), {kb_3} (shotgun) or "
    "{kb_4} (grenade). {kb_backtick} puts a drawn gun away to bare hands, or cycles "
    "your melee - fists, bat, knife. {ms_wheel} steps through every weapon you "
    "are carrying one at a time. {ms_mmb} switches to the next weapon.";

const char* const HELP_DRIVING_KBM =
    "GETTING IN\n"
    "Walk up to a car and press {kb_f} to get in; press {kb_f} again to get "
    "out. Some cars are locked and will not open. To take a car that already "
    "has a driver, stand in front of it and shoot it - the driver may get out, "
    "and then you can get in.\n"
    "\n"
    "DRIVING\n"
    "{kb_w} accelerates and {kb_s} reverses, which also slows you when you are "
    "rolling forward. Steer with {kb_a} and {kb_d}, and swing the camera around "
    "the car with {ms_move}. A car blows up once it takes enough damage, so get "
    "out before a wreck goes up.\n"
    "\n"
    "BRAKE\n"
    "{kb_space} is the brake. At speed it bites hard and throws the car into a "
    "slide toward the way you are steering - handy for police-style turns. It "
    "never reverses; to back up, use {kb_s}.\n"
    "\n"
    "SIREN\n"
    "On emergency vehicles - police cars and ambulances - press {kb_e} to "
    "switch the siren and beacon on and off.";

const char* const HELP_OTHER_KBM =
    "SEARCHING BODIES\n"
    "Hold {kb_f} over a body to search it - a progress bar fills and you may "
    "pull out whatever they were carrying, such as a weapon or ammo. Most of "
    "the time there is nothing.\n"
    "\n"
    "DOORS AND SWITCHES\n"
    "Press {kb_f} at a wall button to push it - these usually open doors. The "
    "round valve handles you find also turn with {kb_f}; some do nothing, others "
    "matter in a mission.\n"
    "\n"
    "TALKING\n"
    "Press {kb_f} next to a person to hear what they have to say - Darci stops "
    "to listen for a moment.\n"
    "\n"
    "HEALTH PACKS\n"
    "Press {kb_f} beside a medkit to use it; Darci only takes it if she is not "
    "at full health.\n"
    "\n"
    "BENCHES\n"
    "Back up to a bench - hold {kb_e} and push back - and Darci sits down on "
    "her own.\n"
    "\n"
    "RIDING ON CARS\n"
    "Jump onto a car with {kb_space} and you can ride on its roof - if someone "
    "else is driving, it carries you along as it goes.\n"
    "\n"
    "PICKUPS\n"
    "Some items scattered around the city raise Darci's abilities - just walk "
    "over one to grab it. You can also pick up an empty can with {kb_f} and "
    "throw it with {ms_lmb}, like a grenade.";
