// PlayStation help bodies. Edit freely. Inline glyph tokens use ps_* ids from
// input_prompt_map. Shared device-agnostic prose lives in help_content_common.h.
// (All topics written: CONTROLS, MOVEMENT, COMBAT, WEAPONS, DRIVING, OTHER.)

#include "ui/menus/help_content_bodies.h"
#include "ui/menus/help_content_common.h"

// Section 1 — full button reference (the "control map"). One line per unique
// control, listing every gameplay situation it is used in (on foot + in a car).
const char* const HELP_CONTROLS_PS =
    HELP_TXT_CONTROLS_INTRO "\n"
    "\n"
    "{ps_rs} - Look around.\n"
    "{ps_r2} - Attack or shoot. In a car: gas.\n"
    "{ps_r1} - Kick.\n"
    "{ps_r3} - Draw or holster your weapon.\n"
    "{ps_r3}+{ps_dpad_up} / {ps_r3}+{ps_dpad_down} - Cycle through "
    "your weapons.\n"
    "{ps_ls} - Move and run. In a car: steering.\n"
    "{ps_cross} - Jump.\n"
    "{ps_circle} - Sprint.\n"
    "{ps_l2} - Slow walk and rolls. In a car: reverse.\n"
    "{ps_square} - Action: get in or out of a car, pick up items, search "
    "bodies, arrest, and interact with the world. Switch target in a fight.\n"
    "{ps_triangle} - Stealth. In a car: siren.\n"
    "{ps_l1} - Zoom in to look around; back-step while moving. In a car: brake.\n"
    "{ps_dpad_up} - Select weapon: pistol.\n"
    "{ps_dpad_left} - Select weapon: M16.\n"
    "{ps_dpad_right} - Select weapon: shotgun.\n"
    "{ps_dpad_up}+{ps_dpad_right} - Select weapon: grenade.\n"
    "{ps_dpad_down} - Switch melee weapon: bat or knife.\n"
    "{ps_start} - Pause.";

const char* const HELP_MOVEMENT_PS =
    "MOVING\n"
    "Run with the {ps_ls}; hold {ps_circle} while running to sprint.\n"
    "Hold {ps_l2} to walk slowly and quietly.\n"
    "Hold {ps_l1} and push back to walk backwards while still facing front; "
    "pushing forward is ignored.\n"
    "\n"
    "CAMERA\n"
    "Move the {ps_rs} to swing the camera; Darci always turns to face where it "
    "points, so you can also steer where she runs by swinging the camera as she "
    "goes. From a standstill, hold {ps_l1} to zoom in for a closer look.\n"
    "\n"
    "JUMPING\n"
    "Tap {ps_cross} to jump, on the spot or along your run. Jump while backing "
    "away to do a backflip.\n"
    "\n"
    "CLIMBING\n"
    "Jump at a ledge to grab on if you reach it; tap {ps_cross} again to climb "
    "up, or edge left and right while hanging.\n"
    "Walk into a ladder to grab on; to get on heading down, back up to it (hold "
    "{ps_l1} and push back) and press {ps_square}. Once on, push forward or back "
    "to climb up or down.\n"
    "Jump onto a wire, often strung between buildings, and Darci catches it and "
    "slides down.\n"
    "\n"
    "ROLLING\n"
    "While moving, tap {ps_l2} with a direction to roll that way.\n"
    "\n"
    "STEALTH\n"
    "From a standstill, hold {ps_triangle} to crouch; then move to crawl on all "
    "fours and stay out of sight.\n"
    "\n"
    "WALL HUG\n"
    "Press {ps_square} against a wall to flatten against it and edge along, left "
    "or right.";

const char* const HELP_COMBAT_PS =
    "FIGHTING STANCE\n"
    "Darci drops into a fighting stance by herself whenever a close fight "
    "starts. In it she stays focused on one enemy - switch target with "
    "{ps_square}. You can't just run out of a fight: roll to break away - any "
    "roll drops the stance, and in a fight you can roll with {ps_l2} or "
    "{ps_cross} as long as you hold a direction. Drawing a gun mid-fight also "
    "drops the stance (a bat or knife does not).\n"
    "\n"
    "STRIKES AND COMBOS\n"
    "Attack with {ps_r2} (hands) or {ps_r1} (feet). Press them a few times, or "
    "alternate the two, to chain a combo - if a follow-up does not come out, "
    "that is normal, the extra hits are not guaranteed. In the stance, hold a "
    "direction with {ps_r1} to kick that way. A bat or knife attacks with "
    "{ps_r2}, and you can still kick.\n"
    "\n"
    "GRAPPLE\n"
    "Press {ps_r2} while moving into an enemy right in front of you to grab "
    "them. From the hold, {ps_r2} tries to throw them down (it can fail and "
    "just shove them away), or {ps_r1} knees them, up to twice if you are "
    "quick. Darci then lets go.\n"
    "\n"
    "DODGE\n"
    "Push back as an enemy attacks and Darci ducks under the blow; hold to stay "
    "low (she stands after a moment). Kick while ducking to sweep nearby enemies "
    "off their feet.\n"
    "\n"
    "RUNNING MOVES\n"
    "Press {ps_r1} while running for a sliding kick that knocks down anyone you "
    "slide into. Jump while running and press {ps_r1} in the air for a flying "
    "kick.\n"
    "\n"
    "DOWNED ENEMIES\n"
    "Stand over an enemy you have knocked down, while they are still alive, and "
    "press {ps_square} to arrest them. Facing a downed enemy up close, press "
    "{ps_r1} to stomp them.";

const char* const HELP_WEAPONS_PS =
    "SHOOTING\n"
    "With a gun out, fire with {ps_r2}. Darci shoots wherever she is facing; she "
    "locks onto people and certain objects near her line of sight so the shot "
    "connects. You can fire on the move as well as standing still. {ps_r2} "
    "fires "
    "one shot from the pistol or shotgun; hold it with the M16 for automatic "
    "fire.\n"
    "\n"
    "RELOADING AND AMMO\n"
    "When a gun runs dry the next {ps_r2} reloads a spare magazine instead of "
    "firing - press again to shoot. With no spares left you just get empty "
    "clicks. Spare ammo and dropped guns are picked up automatically as you walk "
    "over them.\n"
    "\n"
    "GRENADE\n"
    "With the grenade selected, dotted lines show where it will land. Press "
    "{ps_r2} once to pull the pin - a countdown appears by the grenade icon - "
    "and {ps_r2} again to throw it. It goes off when the timer reaches zero, "
    "wherever it is - with the right timing you can make it burst in mid-air.\n"
    "\n"
    "DRAWING AND SWITCHING\n"
    "Pick a gun directly on the {ps_dpad}: {ps_dpad_up} pistol, {ps_dpad_left} "
    "M16, {ps_dpad_right} shotgun, {ps_dpad_up}+{ps_dpad_right} grenade; "
    "{ps_dpad_down} switches between the bat and knife. To step through every "
    "weapon you are carrying, hold {ps_r3} and press {ps_dpad_up} or "
    "{ps_dpad_down}. A tap of {ps_r3} holsters your weapon for bare hands or "
    "draws the last one again.";

const char* const HELP_DRIVING_PS =
    "GETTING IN\n"
    "Walk up to a car and press {ps_square} to get in; press {ps_square} again "
    "to get out. Some cars are locked and will not open. To take a car that "
    "already has a driver, stand in front of it and shoot it - the driver may "
    "get out, and then you can get in.\n"
    "\n"
    "DRIVING\n"
    "{ps_r2} accelerates and {ps_l2} reverses, which also slows you when you are "
    "rolling forward. Steer with the {ps_ls}, and swing the camera around the "
    "car with the {ps_rs}. A car blows up once it takes enough damage, so get "
    "out before a wreck goes up.\n"
    "\n"
    "HANDBRAKE\n"
    "{ps_l1} is a handbrake: tap it to throw the car into a sharp slide toward "
    "the way you are steering - handy for police-style turns. It will slide off "
    "somewhere even if you are driving straight.\n"
    "\n"
    "SIREN\n"
    "On emergency vehicles - police cars and ambulances - press {ps_triangle} "
    "to switch the siren and beacon on and off.";

const char* const HELP_OTHER_PS =
    "SEARCHING BODIES\n"
    "Hold {ps_square} over a body to search it - a progress bar fills and you "
    "may pull out whatever they were carrying, such as a weapon or ammo. Most "
    "of the time there is nothing.\n"
    "\n"
    "DOORS AND SWITCHES\n"
    "Press {ps_square} at a wall button to push it - these usually open doors. "
    "The round valve handles you find also turn with {ps_square}; some do "
    "nothing, others matter in a mission.\n"
    "\n"
    "TALKING\n"
    "Press {ps_square} next to a person to hear what they have to say - Darci "
    "stops to listen for a moment.\n"
    "\n"
    "HEALTH PACKS\n"
    "Press {ps_square} beside a medkit to use it; Darci only takes it if she is "
    "not at full health.\n"
    "\n"
    "BENCHES\n"
    "Back up to a bench - hold {ps_l1} and push back - and Darci sits down on "
    "her own.\n"
    "\n"
    "RIDING ON CARS\n"
    "Jump onto a car with {ps_cross} and you can ride on its roof - if someone "
    "else is driving, it carries you along as it goes.\n"
    "\n"
    "PICKUPS\n"
    "Some items scattered around the city raise Darci's abilities when you "
    "collect them. You can also pick up an empty can with {ps_square} and throw "
    "it with {ps_r2}, like a grenade.";
