#include "ui/input_glyphs/input_glyphs.h"

#include "assets/texture_globals.h" // TEXTURE_page_glyph_*
#include "engine/graphics/graphics_engine/game_graphics_engine.h" // ge_texture_load_rgba
#include "ui/input_glyphs/input_glyph_coords.h" // INPUT_GLYPH_* tables
#include "ui/hud/panel.h" // PANEL_draw_quad
#include "engine/graphics/pipeline/poly.h" // POLY_PAGE_GLYPH_*
#include "engine/graphics/pipeline/polypage.h" // PolyPage UI affine (pixel-snap)
#include "engine/input/gamepad.h" // InputDeviceType
#include "engine/input/gamepad_globals.h" // active_input_device
#include "engine/graphics/text/font2d.h" // FONT2D_*, FONT2D_LETTER_HEIGHT

#include <cstring> // strcmp, strncmp

// stb_image declarations only — the implementation is compiled once in
// assets/formats/stb_image_impl.cpp.
#include "third_party/stb_image.h"

// Embedded PNG byte arrays, generated by CMake from the four atlases in
// src/ui/input_glyphs/assets/ (see CMakeLists.txt "embed_input_glyphs").
#include "input_glyphs_embedded.h"

// Number of RGBA channels we force stb_image to output (R,G,B,A).
#define INPUT_GLYPH_RGBA_CHANNELS 4

// Glyph vertex colour (the glyph page blends with ModulateAlpha, so this
// multiplies the texture's colour AND alpha). The FONT2D text reads slightly
// COOL (greenish-blue) and a touch translucent, so a pure-white opaque glyph
// stands out. We tint the glyph cool (lower red channel → green-blue) and reduce
// alpha to match. ARGB: alpha byte for brightness, RGB for the tint. Tune the
// red channel down for more cool, up toward 0xFF for neutral.
#define INPUT_GLYPH_DRAW_COLOUR 0xA8E0F4F2u

// Extra inter-glyph gap added to a glyph's advance width, as a fraction of the
// drawn glyph width. The 64px source cells already include transparent margin
// around the icon, and rich-text adds real spaces between atoms, so no extra
// padding is needed — kept at 0 (tunable if adjacent glyphs ever look cramped).
#define INPUT_GLYPH_GAP_FRACTION 0.0f

// Whole-pixel vertical nudge (in real framebuffer pixels, positive = down)
// applied to inline glyphs to optically centre them on the visible text.
#define INPUT_GLYPH_VNUDGE_PX 1.0f

namespace {

// Decode one embedded PNG and upload it to its texture page.
void load_atlas(int32_t page, const unsigned char* png, unsigned int png_len)
{
    int w = 0, h = 0, n = 0;
    stbi_uc* data = stbi_load_from_memory(
        png, (int)png_len, &w, &h, &n, INPUT_GLYPH_RGBA_CHANNELS);
    if (data) {
        // Mipmaps on: glyphs are drawn far smaller than the 64px source cells,
        // so trilinear minification keeps thin button outlines from vanishing.
        ge_texture_load_rgba(page, w, h, data, /*gen_mipmaps=*/true);
        stbi_image_free(data);
    }
}

} // namespace

void input_glyphs_init(void)
{
    load_atlas(TEXTURE_page_glyph_kbm, GLYPH_KEYBOARD_PNG, GLYPH_KEYBOARD_PNG_LEN);
    load_atlas(TEXTURE_page_glyph_generic, GLYPH_GENERIC_PNG, GLYPH_GENERIC_PNG_LEN);
    load_atlas(TEXTURE_page_glyph_ps, GLYPH_PS_PNG, GLYPH_PS_PNG_LEN);
    load_atlas(TEXTURE_page_glyph_deck, GLYPH_DECK_PNG, GLYPH_DECK_PNG_LEN);
}

// --- Drawing a logical prompt for the active device ------------------------

namespace {

// One device's atlas: which POLY page to draw on, its coordinate table, and the
// atlas pixel size (square) for UV normalisation.
struct GlyphAtlas {
    SLONG poly_page;
    const InputGlyphRect* table;
    int count;
    int atlas_px;
};

// Pick the atlas matching the active input device. DualSense -> PlayStation
// style, Xbox -> generic (ABXY), everything else -> keyboard & mouse. (Steam
// Deck has no active_input_device value yet, so the `deck` atlas is loaded but
// not selected here — see help_screens devlog follow-ups.)
GlyphAtlas atlas_for_active_device()
{
    switch (active_input_device) {
    case INPUT_DEVICE_DUALSENSE:
        return { POLY_PAGE_GLYPH_PS, INPUT_GLYPH_PS, INPUT_GLYPH_PS_COUNT, INPUT_GLYPH_PS_ATLAS_PX };
    case INPUT_DEVICE_XBOX:
        return { POLY_PAGE_GLYPH_GENERIC, INPUT_GLYPH_GENERIC, INPUT_GLYPH_GENERIC_COUNT, INPUT_GLYPH_GENERIC_ATLAS_PX };
    case INPUT_DEVICE_KEYBOARD_MOUSE:
    default:
        return { POLY_PAGE_GLYPH_KBM, INPUT_GLYPH_KEYBOARD, INPUT_GLYPH_KEYBOARD_COUNT, INPUT_GLYPH_KEYBOARD_ATLAS_PX };
    }
}

// Logical prompt -> Kenney sprite name for the given device family. Mirrors the
// in-game bindings: JUMP = Cross/A/Space, USE = Square/X/F.
const char* sprite_for(InputGlyphKey key, InputDeviceType dev)
{
    const bool xbox = (dev == INPUT_DEVICE_XBOX);
    const bool ps = (dev == INPUT_DEVICE_DUALSENSE);
    switch (key) {
    case INPUT_GLYPH_KEY_JUMP:
        return xbox ? "xbox_button_a" : ps ? "playstation_button_cross" : "keyboard_space";
    case INPUT_GLYPH_KEY_USE:
        return xbox ? "xbox_button_x" : ps ? "playstation_button_square" : "keyboard_f";
    default:
        return nullptr;
    }
}

const InputGlyphRect* find_rect(const InputGlyphRect* table, int count, const char* name)
{
    for (int i = 0; i < count; ++i)
        if (strcmp(table[i].name, name) == 0)
            return &table[i];
    return nullptr;
}

// Round to the nearest integer pixel — keeps glyph edges crisp.
float pixel_snap(float v)
{
    return (float)(SLONG)(v + 0.5f);
}

// "Clean" on-screen glyph sizes in framebuffer pixels: the source cell is 64px,
// so drawing at 64 (native), 32, 16, 8 makes the GPU sample a single mip level
// 1:1 with no trilinear blend (crisp); 128 is a clean 2x magnify. Any size in
// between blends two mip levels and softens. We pick the largest of these that
// fits the reserved box, so glyphs stay sharp instead of blurring at odd sizes.
float clean_glyph_size_px(float box_px)
{
    static const float CLEAN[] = { 128.0f, 64.0f, 32.0f, 16.0f, 8.0f };
    const int n = (int)(sizeof(CLEAN) / sizeof(CLEAN[0]));
    for (int i = 0; i < n; ++i)
        if (CLEAN[i] <= box_px)
            return CLEAN[i];
    return CLEAN[n - 1]; // box smaller than the smallest clean size
}

// Smallest clean size we still treat as "crisp enough". Below this, a clean size
// (16/8) renders the glyph at roughly half the text height — it reads as broken
// next to the letters. So when the box is this small we abandon the clean-size
// rule and resize the glyph to fill the line instead: blurry (off-mip sampling)
// but legible and matched to the text height.
#define GLYPH_CLEAN_MIN_PX 32.0f

// On-screen glyph size (real px) for a reserved box: the crisp clean size when
// that is >= GLYPH_CLEAN_MIN_PX (32+), otherwise the box itself (resize / blur).
float glyph_size_px(float box_px)
{
    const float clean = clean_glyph_size_px(box_px);
    if (clean >= GLYPH_CLEAN_MIN_PX)
        return clean;
    return pixel_snap(box_px);
}

// On-screen geometry of a glyph in virtual 640x480 coords, plus its advance.
// Computed once and shared by draw (needs the quad) and measure (needs only the
// advance), so the size/snap math can never diverge between the two.
struct GlyphLayout {
    float gx, gy, gw, gh; // quad in virtual coords
    float advance; // virtual-px advance (glyph width + inter-glyph gap)
};

// Compute the on-screen layout of a square glyph of size `line_height` (virtual
// coords) placed LEFT-aligned at x and centred vertically within the line
// height. Its footprint/advance is the glyph's own width (+ a small gap), NOT
// the full line-height box, so adjacent prompts don't get large gaps.
//
// Sizing/snapping is done in REAL framebuffer pixels (the UI scope scales
// virtual->real; doing it in virtual would lose the clean-size and pixel-snap
// benefits), then converted back to virtual.
GlyphLayout layout_glyph(float x, float y, float line_height)
{
    float sx = PolyPage::ui_scale_x();
    float sy = PolyPage::ui_scale_y();
    const float ox = PolyPage::ui_offset_x();
    const float oy = PolyPage::ui_offset_y();
    if (sx <= 0.0f) sx = 1.0f;
    if (sy <= 0.0f) sy = 1.0f;

    const float line_h_real = line_height * sy;
    const float g_real = glyph_size_px(line_h_real);

    // Snap both axes to whole framebuffer pixels so the glyph is crisp. The text
    // (FONT2D) now snaps to the same real-pixel grid, so the glyph and the letters
    // share one grid and stay aligned at every UI scale. INPUT_GLYPH_VNUDGE_PX is
    // a whole-real-pixel vertical nudge (down) to optically centre the glyph on
    // the visible text (the letter quad's geometric centre sits a bit high vs the
    // ink).
    const float gx_real = pixel_snap(x * sx + ox);
    const float gy_real = pixel_snap(y * sy + oy + (line_h_real - g_real) * 0.5f) + INPUT_GLYPH_VNUDGE_PX;

    GlyphLayout out;
    out.gx = (gx_real - ox) / sx;
    out.gy = (gy_real - oy) / sy;
    out.gw = g_real / sx;
    out.gh = g_real / sy;

    // Advance = drawn glyph width + a small inter-glyph gap, in virtual coords.
    const float gap_real = pixel_snap(g_real * INPUT_GLYPH_GAP_FRACTION);
    out.advance = (g_real + gap_real) / sx;
    return out;
}

} // namespace

float input_glyph_advance(InputGlyphKey key, float line_height)
{
    const GlyphAtlas a = atlas_for_active_device();
    const char* sprite = sprite_for(key, active_input_device);
    if (!sprite)
        return 0.0f;
    if (!find_rect(a.table, a.count, sprite))
        return 0.0f;
    // Position is irrelevant to the advance; pass 0,0.
    return layout_glyph(0.0f, 0.0f, line_height).advance;
}

float input_glyph_draw(InputGlyphKey key, float x, float y, float line_height, SWORD fade)
{
    const GlyphAtlas a = atlas_for_active_device();
    const char* sprite = sprite_for(key, active_input_device);
    if (!sprite)
        return 0.0f;
    const InputGlyphRect* r = find_rect(a.table, a.count, sprite);
    if (!r)
        return 0.0f;

    const GlyphLayout L = layout_glyph(x, y, line_height);

    const float px = (float)a.atlas_px;
    const float u1 = (float)r->x / px;
    const float v1 = (float)r->y / px;
    const float u2 = (float)(r->x + r->w) / px;
    const float v2 = (float)(r->y + r->h) / px;

    // Scale the base alpha by (255 - fade)/255 so the glyph can fade with text.
    if (fade < 0) fade = 0;
    else if (fade > 255) fade = 255;
    const ULONG base_a = INPUT_GLYPH_DRAW_COLOUR >> 24;
    const ULONG faded_a = base_a * (ULONG)(255 - fade) / 255u;
    const ULONG colour = (INPUT_GLYPH_DRAW_COLOUR & 0x00FFFFFFu) | (faded_a << 24);

    PANEL_draw_quad(L.gx, L.gy, L.gx + L.gw, L.gy + L.gh, a.poly_page,
                    colour, u1, v1, u2, v2);

    return L.advance;
}

// --- Rich text: word-wrapped text with inline input-prompt glyphs ----------

namespace {

// Extra vertical leading between text lines, as a fraction of the text cell
// height. ~40% keeps wrapped lines comfortably separated without looking double
// spaced.
#define INPUT_GLYPH_TEXT_LEADING_FRACTION 0.4f

// FONT2D letter vertical extent relative to the y passed to FONT2D_DrawLetter:
// the letter quad spans (y - TOP) .. (y + BOTTOM*scale/256). TOP is unscaled,
// BOTTOM scales — mirrors font2d.cpp::FONT2D_DrawLetter. Used to align an inline
// glyph's centre to the letter's VISUAL centre (not the line-box centre).
#define FONT2D_LETTER_TOP_PX 3
#define FONT2D_LETTER_BOTTOM_PX 15

// Small empirical vertical nudge (fraction of text height) on top of the
// letter-centre alignment, to centre the glyph against the visible text. With
// per-line baseline pixel-snapping the glyph was sitting low (smaller gap below
// than above), so this lifts it slightly (negative = up). Tune to taste —
// midway between the too-low (+0.04) and too-high (-0.06) trials.
#define INPUT_GLYPH_TEXT_VBIAS_FRACTION 0.00f

// Maps an inline {token} name to a logical prompt. Unknown names are skipped.
struct TokenMap {
    const char* name;
    InputGlyphKey key;
};
const TokenMap INPUT_GLYPH_TOKENS[] = {
    { "jump", INPUT_GLYPH_KEY_JUMP },
    { "use", INPUT_GLYPH_KEY_USE },
};
const int INPUT_GLYPH_TOKEN_COUNT = (int)(sizeof(INPUT_GLYPH_TOKENS) / sizeof(INPUT_GLYPH_TOKENS[0]));

// Resolve a {token} name (length `len`, not NUL-terminated) to a key.
// Returns INPUT_GLYPH_KEY_COUNT if the name is unknown.
InputGlyphKey token_key(const char* name, size_t len)
{
    for (int i = 0; i < INPUT_GLYPH_TOKEN_COUNT; ++i)
        if (strncmp(INPUT_GLYPH_TOKENS[i].name, name, len) == 0 &&
            INPUT_GLYPH_TOKENS[i].name[len] == '\0')
            return INPUT_GLYPH_TOKENS[i].key;
    return INPUT_GLYPH_KEY_COUNT;
}

// Width of one drawn text character in virtual px at `text_scale`. We add the
// +1px the font's own DrawLetter advance includes, so measured width matches
// drawn width and a greedy wrap never overflows by accumulated rounding.
float text_char_width(CBYTE ch, SLONG text_scale)
{
    return (float)(((FONT2D_GetLetterWidth(ch) + 1) * text_scale) >> 8);
}

// Round a virtual-coord Y to a whole VIRTUAL pixel. FONT2D takes an integer y
// ((SLONG)), so giving each line an already-integer baseline means the letters
// and the inline glyph reference the exact same baseline; both then pixel-snap to
// the real framebuffer grid from there, staying aligned at every UI scale.
float round_virtual_y(float vy)
{
    return (float)(SLONG)(vy + 0.5f);
}

// Per-line geometry derived from the text scale, shared by every draw path so
// line spacing / inline-glyph centring can never diverge between them.
struct TextMetrics {
    float text_h;       // text cell height (virtual px)
    float line_advance; // baseline-to-baseline step (cell + leading)
    float space_w;      // width of a separator space
    float glyph_y_off;  // y offset to centre an inline glyph on the letter ink
};

TextMetrics text_metrics(SLONG text_scale)
{
    TextMetrics m;
    m.text_h = (float)((FONT2D_LETTER_HEIGHT * text_scale) >> 8);
    m.line_advance = m.text_h + m.text_h * INPUT_GLYPH_TEXT_LEADING_FRACTION;
    m.space_w = (float)((FONT2D_GetLetterWidth(' ') * text_scale) >> 8);
    // Align an inline glyph's centre to the FONT2D letter's visual centre rather
    // than to the line-box centre (input_glyph_draw centres the glyph in the
    // text_h box we pass), then bias slightly to taste.
    const float letter_centre = (float)(-FONT2D_LETTER_TOP_PX + ((FONT2D_LETTER_BOTTOM_PX * text_scale) >> 8)) * 0.5f;
    m.glyph_y_off = letter_centre - m.text_h * 0.5f + m.text_h * INPUT_GLYPH_TEXT_VBIAS_FRACTION;
    return m;
}

// One wrapped line, as a [begin,end) range into the source string. Re-parsing
// the range with the same atom rules reproduces the exact same layout, so a line
// can be drawn on its own without re-running the wrap.
struct RichLine {
    const char* begin;
    const char* end;
};

// Lay the whole string out into wrapped lines. Records each line's char range
// into out_lines[0..max_lines) and returns the TOTAL line count (which may
// exceed max_lines — extra lines are counted but not stored). Pass out_lines =
// nullptr / max_lines = 0 for a count-only pass.
//
// The wrap is a pure function of (str, wrap_width, text_scale) and the active
// device's glyph advances, so it is deterministic — the same on every call.
int build_lines(const char* str, float wrap_width, SLONG text_scale,
                RichLine* out_lines, int max_lines)
{
    if (!str)
        return 0;

    const TextMetrics m = text_metrics(text_scale);

    int count = 0;
    const char* line_begin = str;
    auto emit = [&](const char* b, const char* e) {
        if (out_lines && count < max_lines)
            out_lines[count] = { b, e };
        ++count;
    };

    float cursor_x = 0.0f; // absolute x cancels out; measure from 0
    bool at_line_start = true;
    bool pending_space = false;

    const char* p = str;
    while (*p) {
        if (*p == '\n') {
            emit(line_begin, p);
            ++p;
            line_begin = p;
            cursor_x = 0.0f;
            at_line_start = true;
            pending_space = false;
            continue;
        }
        if (*p == ' ') {
            pending_space = true;
            ++p;
            continue;
        }

        // Parse one atom: a {token} glyph or a run of normal characters (measure).
        const char* atom_begin = p;
        float atom_w = 0.0f;
        bool is_glyph = false;

        if (*p == '{') {
            const char* close = p + 1;
            while (*close && *close != '}')
                ++close;
            if (*close == '}') {
                InputGlyphKey k = token_key(p + 1, (size_t)(close - (p + 1)));
                p = close + 1;
                if (k != INPUT_GLYPH_KEY_COUNT) {
                    is_glyph = true;
                    atom_w = input_glyph_advance(k, m.text_h);
                } else {
                    // Unknown token: skip entirely (no advance, no wrap).
                    continue;
                }
            } else {
                // Unterminated '{': treat as a normal word starting at '{'.
                while (*p && *p != ' ' && *p != '\n')
                    ++p;
                for (const char* c = atom_begin; c < p; ++c)
                    atom_w += text_char_width((CBYTE)*c, text_scale);
            }
        } else {
            while (*p && *p != ' ' && *p != '\n' && *p != '{')
                ++p;
            for (const char* c = atom_begin; c < p; ++c)
                atom_w += text_char_width((CBYTE)*c, text_scale);
        }
        (void)is_glyph;

        const float lead = (pending_space && !at_line_start) ? m.space_w : 0.0f;

        // Wrap before placing this atom if it would overflow (never wrap at line
        // start — a single over-wide atom just overflows rather than looping).
        if (!at_line_start && cursor_x + lead + atom_w > wrap_width) {
            emit(line_begin, atom_begin);
            line_begin = atom_begin;
            cursor_x = 0.0f;
            at_line_start = true;
        }

        if (pending_space && !at_line_start)
            cursor_x += m.space_w;
        pending_space = false;
        cursor_x += atom_w;
        at_line_start = false;
    }

    emit(line_begin, p); // final line
    return count;
}

// Draw one already-laid-out line at (x, y). Walks the line's char range with the
// same atom/spacing rules build_lines used, so positions match exactly. Does NOT
// wrap (the line is known to fit).
void draw_one_line(const RichLine& line, float x, float y, SLONG text_scale,
                   unsigned long colour, SWORD fade, const TextMetrics& m)
{
    float cursor_x = x;
    bool at_line_start = true;
    bool pending_space = false;

    const char* p = line.begin;
    while (p < line.end) {
        if (*p == ' ') {
            pending_space = true;
            ++p;
            continue;
        }

        const char* atom_begin = p;
        bool is_glyph = false;
        InputGlyphKey glyph_key = INPUT_GLYPH_KEY_COUNT;

        if (*p == '{') {
            const char* close = p + 1;
            while (close < line.end && *close != '}')
                ++close;
            if (close < line.end && *close == '}') {
                glyph_key = token_key(p + 1, (size_t)(close - (p + 1)));
                p = close + 1;
                if (glyph_key != INPUT_GLYPH_KEY_COUNT) {
                    is_glyph = true;
                } else {
                    continue; // unknown token: skip
                }
            } else {
                while (p < line.end && *p != ' ')
                    ++p;
            }
        } else {
            while (p < line.end && *p != ' ' && *p != '{')
                ++p;
        }

        if (pending_space && !at_line_start)
            cursor_x += m.space_w;
        pending_space = false;

        if (is_glyph) {
            cursor_x += input_glyph_draw(glyph_key, cursor_x, y + m.glyph_y_off, m.text_h, fade);
        } else {
            for (const char* c = atom_begin; c < p; ++c)
                cursor_x += (float)FONT2D_DrawLetter(
                    (CBYTE)*c, (SLONG)cursor_x, (SLONG)y, colour, text_scale,
                    POLY_PAGE_FONT2D, fade);
        }
        at_line_start = false;
    }
}

// Upper bound on wrapped lines laid out at once. Help bodies are far shorter;
// any excess is counted (for scroll bounds) but not stored/drawn.
const int RICH_TEXT_MAX_LINES = 256;

} // namespace

float input_glyph_text_draw(const char* str, float x, float y, float wrap_width,
                            SLONG text_scale, unsigned long colour, SWORD fade)
{
    if (!str)
        return 0.0f;

    const TextMetrics m = text_metrics(text_scale);

    RichLine lines[RICH_TEXT_MAX_LINES];
    const int total = build_lines(str, wrap_width, text_scale, lines, RICH_TEXT_MAX_LINES);
    const int stored = (total < RICH_TEXT_MAX_LINES) ? total : RICH_TEXT_MAX_LINES;

    float ly = round_virtual_y(y);
    for (int i = 0; i < stored; ++i) {
        draw_one_line(lines[i], x, ly, text_scale, colour, fade, m);
        ly = round_virtual_y(ly + m.line_advance);
    }

    return (float)total * m.line_advance;
}

SLONG input_glyph_text_draw_scrolled(const char* str, float x, float y,
                                     float wrap_width, SLONG text_scale,
                                     unsigned long colour, SWORD fade,
                                     SLONG* first_line, float view_height,
                                     SLONG* out_fit)
{
    const TextMetrics m = text_metrics(text_scale);

    RichLine lines[RICH_TEXT_MAX_LINES];
    const int total = build_lines(str, wrap_width, text_scale, lines, RICH_TEXT_MAX_LINES);
    const int stored = (total < RICH_TEXT_MAX_LINES) ? total : RICH_TEXT_MAX_LINES;

    // How many WHOLE lines fit the window (floor — no partial line peeks at the
    // bottom edge, which is what lets us skip clipping entirely).
    int fit = (m.line_advance > 0.0f) ? (int)(view_height / m.line_advance) : 0;
    if (fit < 1)
        fit = 1;

    // Clamp the caller's scroll to a valid first-line and write it back.
    int first = first_line ? (int)*first_line : 0;
    int max_first = total - fit;
    if (max_first < 0)
        max_first = 0;
    if (first < 0)
        first = 0;
    if (first > max_first)
        first = max_first;
    if (first_line)
        *first_line = (SLONG)first;
    if (out_fit)
        *out_fit = (SLONG)fit;

    const int last = (first + fit < stored) ? (first + fit) : stored;
    float ly = round_virtual_y(y);
    for (int i = first; i < last; ++i) {
        draw_one_line(lines[i], x, ly, text_scale, colour, fade, m);
        ly = round_virtual_y(ly + m.line_advance);
    }

    return (SLONG)total;
}
