// Sets up Direct3D render states for all poly pages. Each page has a specific texture
// and blend mode. Also handles sorting pages by texture for fewer state switches.

#include "engine/platform/platform.h"
#include <math.h>
#include "engine/graphics/pipeline/poly_render.h"
#include "engine/graphics/pipeline/poly_render_globals.h"
#include "engine/graphics/pipeline/poly.h"
#include "engine/graphics/pipeline/polypage.h"
#include "engine/graphics/pipeline/render_state.h"
#include "engine/graphics/graphics_api/gd_display.h"
#include "assets/texture.h"

// DefRenderState is defined in poly.cpp (not yet migrated).
// uc_orig: DefRenderState (fallen/DDEngine/Source/poly.cpp)
extern RenderState DefRenderState;

// RenderStates_OK: prevents re-initialising render states every frame.
// Was file-private in original. Kept in .cpp — it's implementation state, not a global.
// uc_orig: RenderStates_OK (fallen/DDEngine/Source/polyrenderstate.cpp)
static bool RenderStates_OK = false;

// Convenience macros to set PolyPage state (locally to this file).
// These were #define-only in the original.
#undef SET_TEXTURE
#undef SET_NO_TEXTURE
#undef SET_RENDER_STATE

#define SET_TEXTURE(PAGE)                               \
    {                                                   \
        pa->RS.SetTexture(TEXTURE_get_handle(PAGE));    \
        pa->SetTexOffset(TEXTURE_get_D3DTexture(PAGE)); \
    }
#define SET_NO_TEXTURE pa->RS.SetTexture(NULL)
#define SET_RENDER_STATE(I, V) pa->RS.SetRenderState(I, V)
#define SET_EFFECT(FX) pa->RS.SetEffect(FX)

// uc_orig: POLY_reset_render_states (fallen/DDEngine/Source/polyrenderstate.cpp)
void POLY_reset_render_states()
{
    RenderStates_OK = false;
}

// uc_orig: POLY_init_texture_flags (fallen/DDEngine/Source/polyrenderstate.cpp)
void POLY_init_texture_flags(void)
{
    POLY_reset_render_states();
    memset(POLY_page_flag, 0, sizeof(POLY_page_flag));
}

// uc_orig: POLY_load_texture_flags (fallen/DDEngine/Source/polyrenderstate.cpp)
void POLY_load_texture_flags(CBYTE* fname, SLONG offset)
{
    FILE* handle = MF_Fopen(fname, "rb");

    if (handle) {
        CBYTE line[256];
        SLONG match;
        SLONG page = 0;

        while (fgets(line, 256, handle)) {
            match = sscanf(line, "Page %d:", &page);

            page += offset;

            if (match == 1 && WITHIN(page, 0, POLY_NUM_PAGES - 1)) {
                CBYTE* c;

                for (c = line; *c; c++)
                    ; // Zoom to the end of the line.

                while (1) {
                    c--;

                    if (*c == 'T' || *c == 't') {
                        POLY_page_flag[page] |= POLY_PAGE_FLAG_TRANSPARENT;
                    } else if (*c == 'W' || *c == 'w') {
                        POLY_page_flag[page] |= POLY_PAGE_FLAG_WRAP;
                    } else if (*c == 'A' || *c == 'a') {
                        POLY_page_flag[page] |= POLY_PAGE_FLAG_ADD_ALPHA;
                    } else if (*c == 'I' || *c == 'i') {
                        if (WITHIN(page, 0, POLY_NUM_PAGES - 2)) {
                            POLY_page_flag[page + 0] |= POLY_PAGE_FLAG_2PASS;
                            POLY_page_flag[page + 1] |= POLY_PAGE_FLAG_TRANSPARENT;
                            POLY_page_flag[page + 1] |= POLY_PAGE_FLAG_SELF_ILLUM;
                        }
                    } else if (*c == 'S' || *c == 's') {
                        POLY_page_flag[page] |= POLY_PAGE_FLAG_SELF_ILLUM;
                    } else if (*c == 'F' || *c == 'f') {
                        POLY_page_flag[page] |= POLY_PAGE_FLAG_NO_FOG;
                    } else if (*c == 'D' || *c == 'd') {
                        if (WITHIN(page, 0, POLY_NUM_PAGES - 2)) {
                            POLY_page_flag[page + 0] |= POLY_PAGE_FLAG_2PASS | POLY_PAGE_FLAG_WINDOW;
                            POLY_page_flag[page + 1] |= POLY_PAGE_FLAG_WINDOW_2ND;
                        }
                    } else if (*c == 'M' || *c == 'm') {
                        POLY_page_flag[page] |= POLY_PAGE_FLAG_ALPHA;
                    } else if (*c == ':') {
                        break;
                    }
                }
            }
        }

        MF_Fclose(handle);
    }
}

// uc_orig: POLY_init_render_states (fallen/DDEngine/Source/polyrenderstate.cpp)
// Initialises D3D render states for each poly page based on its page ID and flags.
// Also sorts pages by texture handle to reduce state changes during rendering.
void POLY_init_render_states()
{
    if (RenderStates_OK)
        return;

    // AENG_detail_filter is defined in aeng.cpp (not yet migrated).
    // uc_orig: AENG_detail_filter (fallen/DDEngine/Source/aeng.cpp)
    extern int AENG_detail_filter;

    if (!AENG_detail_filter) {
        DefRenderState = RenderState(D3DFILTER_NEAREST, D3DFILTER_NEAREST);
    } else {
        DefRenderState = RenderState(D3DFILTER_LINEAR, D3DFILTER_LINEAR);
    }

    // Set each page to the default render state.
    for (int ii = 0; ii < POLY_NUM_PAGES; ii++) {
        POLY_Page[ii].RS = DefRenderState;
    }

    // Override per-page render states based on page type.
    PolyPage* pa;

    for (int ii = 0; ii < POLY_NUM_PAGES; ii++) {
        pa = &POLY_Page[ii];

        {
            // Default is on!
            SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_TRUE);

            // set using the old interface
            switch (ii) {
            case POLY_PAGE_LADSHAD:
                SET_TEXTURE((TEXTURE_page_ladshad));
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREADDRESS, D3DTADDRESS_WRAP);
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATEALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_INVSRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                break;

            case POLY_PAGE_SIGN:
                SET_TEXTURE((TEXTURE_page_sign));
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATEALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_INVSRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                break;

            case POLY_PAGE_LASTPANEL_ALPHA:
                SET_TEXTURE((TEXTURE_page_lastpanel));
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATEALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_INVSRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);

                break;

            case POLY_PAGE_LASTPANEL_ADDALPHA:
                SET_TEXTURE((TEXTURE_page_lastpanel));
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATEALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_ONE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_EFFECT(RS_AlphaPremult);

                break;

            case POLY_PAGE_LASTPANEL_ADD:
                SET_TEXTURE((TEXTURE_page_lastpanel));
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_ONE);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_ONE);

                break;

            case POLY_PAGE_LASTPANEL_SUB:
                SET_TEXTURE((TEXTURE_page_lastpanel));
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_ZERO);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_INVSRCALPHA);
                SET_EFFECT(RS_BlackWithAlpha);
                break;

            case POLY_PAGE_LASTPANEL2_ADD:
                SET_TEXTURE((TEXTURE_page_lastpanel2));
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_ONE);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_ONE);

                break;

            case POLY_PAGE_LASTPANEL2_ADDALPHA:
                SET_TEXTURE((TEXTURE_page_lastpanel2));
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_ONE);
                SET_EFFECT(RS_AlphaPremult);

                break;

            case POLY_PAGE_LASTPANEL2_SUB:
                SET_TEXTURE((TEXTURE_page_lastpanel2));
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_ZERO);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_INVSRCALPHA);
                SET_EFFECT(RS_BlackWithAlpha);
                break;

            case POLY_PAGE_LASTPANEL2_ALPHA:
                SET_TEXTURE((TEXTURE_page_lastpanel2));
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATEALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_INVSRCALPHA);

                break;

            case POLY_PAGE_LITE_BOLT:
                SET_TEXTURE((TEXTURE_page_litebolt));
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_ONE);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_ONE);
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREADDRESS, D3DTADDRESS_WRAP);
                break;

            case POLY_PAGE_SHADOW_OVAL:
                SET_TEXTURE((TEXTURE_page_shadowoval));
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATEALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_INVSRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);

                break;

            case POLY_PAGE_SHADOW_SQUARE:
                SET_TEXTURE((TEXTURE_page_shadowsquare));
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATEALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_INVSRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                break;

            case POLY_PAGE_FADECAT:
                SET_TEXTURE((TEXTURE_page_fadecat));
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATEALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_INVSRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_ZENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                break;

            case POLY_PAGE_FADE_MF:
                SET_TEXTURE((TEXTURE_page_fade_MF));
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATEALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_INVSRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_ZENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                break;

            case POLY_PAGE_LADDER:
                SET_TEXTURE((TEXTURE_page_ladder));
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREADDRESS, D3DTADDRESS_WRAP);

                break;

            case POLY_PAGE_FINALGLOW:
                SET_TEXTURE((TEXTURE_page_finalglow));
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_ONE);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_ONE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                break;

            case POLY_PAGE_IC2_NORMAL:
                SET_TEXTURE((TEXTURE_page_ic2));
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZENABLE, UC_FALSE);
                break;

            case POLY_PAGE_IC_NORMAL:
                SET_TEXTURE((TEXTURE_page_ic));
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZENABLE, UC_FALSE);
                break;

            case POLY_PAGE_IC2_ALPHA:
            case POLY_PAGE_IC2_ALPHA_END:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATEALPHA);
                SET_TEXTURE((TEXTURE_page_ic2));
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_INVSRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                break;

            case POLY_PAGE_IC_ALPHA:
            case POLY_PAGE_IC_ALPHA_END:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATEALPHA);
                SET_TEXTURE((TEXTURE_page_ic));
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_INVSRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                break;

            case POLY_PAGE_IC2_ADDITIVE:
                SET_TEXTURE((TEXTURE_page_ic2));
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_ONE);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_ONE);
                break;

            case POLY_PAGE_IC_ADDITIVE:
                SET_TEXTURE((TEXTURE_page_ic));
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_ONE);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_ONE);
                break;

            case POLY_PAGE_PRESS1:
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                TEXTURE_set_colour_key(TEXTURE_page_press1);
                SET_RENDER_STATE(D3DRENDERSTATE_COLORKEYENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZENABLE, UC_FALSE);
                SET_TEXTURE((TEXTURE_page_press1));
                break;

            case POLY_PAGE_PRESS2:
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                TEXTURE_set_colour_key(TEXTURE_page_press2);
                SET_RENDER_STATE(D3DRENDERSTATE_COLORKEYENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZENABLE, UC_FALSE);
                SET_TEXTURE((TEXTURE_page_press2));
                break;

            case POLY_PAGE_TARGET:
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                TEXTURE_set_colour_key(TEXTURE_page_target);
                SET_RENDER_STATE(D3DRENDERSTATE_COLORKEYENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZENABLE, UC_FALSE);
                SET_TEXTURE((TEXTURE_page_target));
                break;

            case POLY_PAGE_DEVIL:
                SET_TEXTURE((TEXTURE_page_devil));
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_DECAL);
                break;

            case POLY_PAGE_ANGEL:
                SET_TEXTURE((TEXTURE_page_angel));
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_DECAL);
                break;

            case POLY_PAGE_LEAF:
                SET_TEXTURE((TEXTURE_page_leaf));
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHATESTENABLE, UC_TRUE);

                break;

            case POLY_PAGE_RUBBISH:
                SET_TEXTURE((TEXTURE_page_rubbish));
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHATESTENABLE, UC_TRUE);

                break;

            case POLY_PAGE_WINMAP:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_ONE);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_ONE);
                SET_TEXTURE((TEXTURE_page_winmap));
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREADDRESS, D3DTADDRESS_WRAP);

                break;

            case POLY_PAGE_ENVMAP:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_ONE);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_ONE);
                SET_TEXTURE((TEXTURE_page_envmap));
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREADDRESS, D3DTADDRESS_WRAP);
                break;

            case POLY_PAGE_SEWATER:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATEALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_INVSRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_TEXTURE((TEXTURE_page_water));
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREADDRESS, D3DTADDRESS_WRAP);
                break;

            case POLY_PAGE_SKY:
                SET_TEXTURE((TEXTURE_page_sky));
                // Z-buffered since sky is no longer drawn first.
                SET_RENDER_STATE(D3DRENDERSTATE_ZENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                break;

            case POLY_PAGE_SHADOW:
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);

                if (the_display.GetDeviceInfo()->DestInvSourceColourSupported()) {
                    // use a density greyscale shadowmap
                    SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                    SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_ZERO);
                    SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_INVSRCCOLOR);
                } else {
                    // use a density alpha (+black) shadowmap
                    SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATEALPHA);
                    SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                    SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_INVSRCALPHA);
                }

                SET_TEXTURE((TEXTURE_page_shadow));
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZBIAS, 8);
                break;

            case POLY_PAGE_TEST_SHADOWMAP:
                if (the_display.GetDeviceInfo()->DestInvSourceColourSupported()) {
                    SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                    SET_TEXTURE(TEXTURE_page_shadow);
                    SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                }
                break;

            case POLY_PAGE_PUDDLE:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATEALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_INVSRCALPHA);
                SET_TEXTURE((TEXTURE_page_puddle));
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHATESTENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                break;

            case POLY_PAGE_MOON:
                SET_TEXTURE((TEXTURE_page_moon));
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_ONE);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_ONE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                break;

            case POLY_PAGE_MANONMOON:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATEALPHA);
                SET_TEXTURE((571));
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_INVSRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZENABLE, UC_FALSE);
                break;

            case POLY_PAGE_CLOUDS:
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_INVSRCALPHA);
                SET_TEXTURE((TEXTURE_page_clouds));
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                break;

            case POLY_PAGE_ALPHA:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATEALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_INVSRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_NO_TEXTURE;
                break;

            case POLY_PAGE_ALPHA_OVERLAY:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATEALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_INVSRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_NO_TEXTURE;
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZENABLE, UC_FALSE);
                break;

            case POLY_PAGE_ADDITIVE:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_ONE);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_ONE);
                SET_NO_TEXTURE;
                break;

            case POLY_PAGE_ADDITIVEALPHA:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_ONE);
                SET_NO_TEXTURE;
                SET_EFFECT(RS_AlphaPremult);
                break;

            case POLY_PAGE_MASKED:
                SET_TEXTURE(-1);
                TEXTURE_set_colour_key(0);
                SET_RENDER_STATE(D3DRENDERSTATE_COLORKEYENABLE, UC_TRUE);
                break;

            case POLY_PAGE_FACE1:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAG, D3DFILTER_NEAREST);
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMIN, D3DFILTER_NEAREST);
                SET_TEXTURE((TEXTURE_page_face1));
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);

                break;

            case POLY_PAGE_FACE2:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAG, D3DFILTER_NEAREST);
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMIN, D3DFILTER_NEAREST);
                SET_TEXTURE((TEXTURE_page_face2));
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);

                break;

            case POLY_PAGE_FACE3:
                SET_TEXTURE((TEXTURE_page_face3));
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                break;

            case POLY_PAGE_FACE4:
                SET_TEXTURE((TEXTURE_page_face4));
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                break;

            case POLY_PAGE_FACE5:
                SET_TEXTURE((TEXTURE_page_face5));
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                break;

            case POLY_PAGE_FACE6:
                SET_TEXTURE((TEXTURE_page_face6));
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                break;

            case POLY_PAGE_COLOUR_ALPHA:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_INVSRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                SET_NO_TEXTURE;

                break;

            case POLY_PAGE_COLOUR:
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                SET_NO_TEXTURE;

                break;

            case POLY_PAGE_COLOUR_WITH_FOG:
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_TRUE);
                SET_NO_TEXTURE;
                break;

            case POLY_PAGE_WATER:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_INVSRCALPHA);
                SET_TEXTURE((TEXTURE_page_water));
                break;

            case POLY_PAGE_DRIP:
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_ONE);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_ONE);
                SET_TEXTURE((TEXTURE_page_drip));
                break;

            case POLY_PAGE_FOG:
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATEALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_ONE);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_ONE);
                SET_TEXTURE((TEXTURE_page_fog));
                break;

            case POLY_PAGE_STEAM:
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_ONE);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_ONE);
                SET_TEXTURE((TEXTURE_page_steam));
                break;

            case POLY_PAGE_BANG:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_ONE);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_ONE);
                SET_TEXTURE((TEXTURE_page_bang));
                break;

            case POLY_PAGE_TEXT:
                SET_RENDER_STATE(D3DRENDERSTATE_ZENABLE, UC_FALSE);
                SET_TEXTURE((TEXTURE_page_font));
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_ONE);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_ONE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                break;

            case POLY_PAGE_LOGO:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATEALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_INVSRCALPHA);
                SET_TEXTURE((TEXTURE_page_logo));
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                break;

            case POLY_PAGE_DROPLET:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_ONE);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_ONE);
                SET_TEXTURE((TEXTURE_page_droplet));
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                break;

            case POLY_PAGE_RAINDROP:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATEALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_INVSRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_TEXTURE((TEXTURE_page_raindrop));
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                break;

            case POLY_PAGE_SPARKLE:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_ONE);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_ONE);
                SET_TEXTURE((TEXTURE_page_sparkle));
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                break;

            case POLY_PAGE_FLAMES:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_ONE);
                SET_TEXTURE((TEXTURE_page_flames));
                SET_EFFECT(RS_AlphaPremult);
                break;

            case POLY_PAGE_FLAMES2:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATEALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_ONE);
                SET_TEXTURE((TEXTURE_page_flame2));
                SET_EFFECT(RS_AlphaPremult);

                break;

            case POLY_PAGE_SMOKE:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_ZERO);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_INVSRCCOLOR);
                SET_TEXTURE((TEXTURE_page_smoke));
                break;

            case POLY_PAGE_MENUFLAME:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_ONE);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_ONE);
                SET_TEXTURE((TEXTURE_page_menuflame));
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREADDRESS, D3DTADDRESS_WRAP);
                break;

            case POLY_PAGE_MENUTEXT:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZBIAS, 0);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_ONE);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_ONE);
                SET_TEXTURE((TEXTURE_page_flames));
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREADDRESS, D3DTADDRESS_WRAP);
                break;

            case POLY_PAGE_MENUPASS:
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_TEXTURE((TEXTURE_page_moon));
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                TEXTURE_set_colour_key(TEXTURE_page_moon);
                SET_RENDER_STATE(D3DRENDERSTATE_COLORKEYENABLE, UC_TRUE);
                break;

            case POLY_PAGE_BARBWIRE:
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_INVSRCALPHA);
                SET_TEXTURE((TEXTURE_page_barbwire));
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                break;

            case POLY_PAGE_FOOTPRINT:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATEALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_INVSRCALPHA);
                SET_TEXTURE((TEXTURE_page_footprint));
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_TRUE);
                break;

            case POLY_PAGE_FONT2D:
                SET_RENDER_STATE(D3DRENDERSTATE_ZENABLE, UC_FALSE);
                SET_TEXTURE((TEXTURE_page_font2d));
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATEALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAG, D3DFILTER_LINEAR);
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMIN, D3DFILTER_LINEAR);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_INVSRCALPHA);

                break;

            case POLY_PAGE_BIGBANG:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_INVSRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_ONE);
                SET_TEXTURE((TEXTURE_page_bigbang));
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREADDRESS, D3DTADDRESS_WRAP);
                SET_EFFECT(RS_InvAlphaPremult);

                break;

            case POLY_PAGE_FLAMES3:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_INVSRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_ONE);
                SET_TEXTURE((TEXTURE_page_flames3));
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREADDRESS, D3DTADDRESS_WRAP);
                SET_EFFECT(RS_InvAlphaPremult);
                break;

            case POLY_PAGE_DUSTWAVE:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_INVSRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_ONE);
                SET_TEXTURE((TEXTURE_page_dustwave));
                SET_EFFECT(RS_InvAlphaPremult);

                break;

            case POLY_PAGE_BLOODSPLAT:
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATEALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_INVSRCALPHA);
                SET_TEXTURE((TEXTURE_page_bloodsplat));
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_TRUE);

                break;

            case POLY_PAGE_BLOOM1:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_ONE);
                SET_TEXTURE((TEXTURE_page_bloom1));
                SET_EFFECT(RS_AlphaPremult);

                break;

            case POLY_PAGE_BLOOM2:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_ONE);
                SET_TEXTURE((TEXTURE_page_bloom2));
                SET_EFFECT(RS_AlphaPremult);
                break;

            case POLY_PAGE_SNOWFLAKE:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_ONE);
                SET_TEXTURE((TEXTURE_page_snowflake));

                break;
            case POLY_PAGE_HITSPANG:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_ONE);
                SET_TEXTURE((TEXTURE_page_hitspang));
                SET_EFFECT(RS_AlphaPremult);
                break;

            case POLY_PAGE_LENSFLARE:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_ONE);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_ONE);
                SET_TEXTURE((TEXTURE_page_lensflare));
                break;

            case POLY_PAGE_TYRETRACK:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATEALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_INVSRCALPHA);
                SET_TEXTURE((TEXTURE_page_tyretrack_alpha));
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_TRUE);
                break;

            case POLY_PAGE_TYRESKID:
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATEALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_ZERO);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_INVSRCALPHA);
                SET_TEXTURE((TEXTURE_page_tyretrack));
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZBIAS, 4);
                SET_EFFECT(RS_BlackWithAlpha);
                break;

            case POLY_PAGE_NEWFONT_INVERSE:
                // All the alternatives in the original were commented out; only the final version
                // that uses TEXTURE_page_lcdfont with additive blending remains.
                SET_TEXTURE((TEXTURE_page_lcdfont));
                SET_RENDER_STATE(D3DRENDERSTATE_ZENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_ONE);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_ONE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);

                break;

            case POLY_PAGE_MENULOGO:
                SET_RENDER_STATE(D3DRENDERSTATE_ZENABLE, UC_FALSE);
                SET_TEXTURE((TEXTURE_page_menulogo));
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATEALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_INVSRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                break;

            case POLY_PAGE_POLAROID:
                SET_TEXTURE((TEXTURE_page_polaroid));
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_DECAL);

                break;

            case POLY_PAGE_SMOKER:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_ONE);
                SET_TEXTURE((TEXTURE_page_smoker));
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREADDRESS, D3DTADDRESS_WRAP);
                SET_EFFECT(RS_AlphaPremult);
                break;

            case POLY_PAGE_NEWFONT:
                SET_RENDER_STATE(D3DRENDERSTATE_ZENABLE, UC_FALSE);
                SET_TEXTURE((TEXTURE_page_lcdfont));
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATEALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_ZERO);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_INVSRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                SET_EFFECT(RS_BlackWithAlpha);
                break;

            case POLY_PAGE_EXPLODE1:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAG, D3DFILTER_NEAREST);
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMIN, D3DFILTER_NEAREST);
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATEALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_INVSRCALPHA);
                SET_TEXTURE((TEXTURE_page_explode1));

                break;

            case POLY_PAGE_EXPLODE2:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAG, D3DFILTER_NEAREST);
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMIN, D3DFILTER_NEAREST);
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATEALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_INVSRCALPHA);
                SET_TEXTURE((TEXTURE_page_explode2));

                break;

            case POLY_PAGE_EXPLODE1_ADDITIVE:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATEALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_ONE);
                SET_TEXTURE((TEXTURE_page_explode1));
                SET_EFFECT(RS_AlphaPremult);

                break;

            case POLY_PAGE_EXPLODE2_ADDITIVE:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATEALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_ONE);
                SET_TEXTURE((TEXTURE_page_explode2));
                SET_EFFECT(RS_AlphaPremult);

                break;

            case POLY_PAGE_SPLASH:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_INVSRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_ONE);
                SET_TEXTURE((TEXTURE_page_splash));
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREADDRESS, D3DTADDRESS_WRAP);
                SET_EFFECT(RS_InvAlphaPremult);
                break;

            case POLY_PAGE_METEOR:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATEALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_ONE);
                SET_TEXTURE((TEXTURE_page_meteor));
                SET_EFFECT(RS_AlphaPremult);
                break;

            case POLY_PAGE_SUBTRACTIVEALPHA:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_ZERO);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_INVSRCALPHA);
                SET_NO_TEXTURE;
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                SET_EFFECT(RS_BlackWithAlpha);
                break;

            case POLY_PAGE_SMOKECLOUD:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATEALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_ZERO);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_INVSRCALPHA);
                SET_TEXTURE((TEXTURE_page_smokecloud));
                SET_EFFECT(RS_BlackWithAlpha);
                break;

            case POLY_PAGE_SMOKECLOUD2:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATEALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_INVSRCALPHA);
                SET_TEXTURE((TEXTURE_page_smokecloud));

                break;

            case POLY_PAGE_BIG_BUTTONS:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_DECAL);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_INVSRCALPHA);
                SET_TEXTURE((TEXTURE_page_bigbutton));
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                break;

            case POLY_PAGE_TINY_BUTTONS:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATEALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_INVSRCALPHA);
                SET_TEXTURE((TEXTURE_page_tinybutt));
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                break;

            case POLY_PAGE_BIG_LEAF:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATE);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_INVSRCALPHA);
                SET_TEXTURE((TEXTURE_page_bigleaf));
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                break;

            case POLY_PAGE_BIG_RAIN:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATEALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_ONE);
                SET_TEXTURE((TEXTURE_page_bigrain));
                SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                SET_EFFECT(RS_AlphaPremult);
                break;

            case POLY_PAGE_PCFLAMER:
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_MODULATEALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_INVSRCALPHA);
                SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_ONE);
                SET_TEXTURE((TEXTURE_page_pcflamer));
                SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREADDRESS, D3DTADDRESS_WRAP);
                SET_EFFECT(RS_InvAlphaPremult);

                break;

            default:
                // Standard texture pages: apply per-page flags.
                if (ii < TEXTURE_page_num_standard && !(draw_3d && (ii == 510 || ii == 511))) {
                    SET_TEXTURE((ii));

                    if (POLY_page_flag[ii]) {
                        if (POLY_page_flag[ii] & POLY_PAGE_FLAG_TRANSPARENT) {
                            bool use_chroma = false;

                            if (POLY_page_flag[ii] & POLY_PAGE_FLAG_SELF_ILLUM) {
                                if (the_display.GetDeviceInfo()->DestInvSourceColourSupported() && !the_display.GetDeviceInfo()->ModulateAlphaSupported()) {
                                    // it's a RagePro, so use chroma keying
                                    use_chroma = true;
                                }
                            }

                            if (use_chroma) {
                                // use colour keying to make the windows work on the Rage Pro
                                TEXTURE_set_colour_key(ii);
                                SET_RENDER_STATE(D3DRENDERSTATE_COLORKEYENABLE, UC_TRUE);
                            } else {
                                SET_RENDER_STATE(D3DRENDERSTATE_ALPHATESTENABLE, UC_TRUE);
                            }
                        }

                        if (POLY_page_flag[ii] & POLY_PAGE_FLAG_WRAP) {
                            SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREADDRESS, D3DTADDRESS_WRAP);
                        }

                        if (POLY_page_flag[ii] & POLY_PAGE_FLAG_ADD_ALPHA) {
                            SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                            SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                            SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_ONE);
                            SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_ONE);
                        }

                        if ((POLY_page_flag[ii] & POLY_PAGE_FLAG_SELF_ILLUM) && !draw_3d) {
                            SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_DECAL);
                        }

                        if (POLY_page_flag[ii] & POLY_PAGE_FLAG_NO_FOG) {
                            SET_RENDER_STATE(D3DRENDERSTATE_FOGENABLE, UC_FALSE);
                        }

                        if (POLY_page_flag[ii] & POLY_PAGE_FLAG_WINDOW) {
                            SET_RENDER_STATE(D3DRENDERSTATE_ALPHATESTENABLE, UC_TRUE);

                            SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                            SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_ONE);
                            SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_ONE);
                        }

                        if (POLY_page_flag[ii] & POLY_PAGE_FLAG_WINDOW_2ND) {
                            SET_RENDER_STATE(D3DRENDERSTATE_ZFUNC, D3DCMP_LESS);
                        }

                        if (POLY_page_flag[ii] & POLY_PAGE_FLAG_ALPHA) {
                            SET_RENDER_STATE(D3DRENDERSTATE_ZWRITEENABLE, UC_FALSE);
                            SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                            SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_SRCALPHA);
                            SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_INVSRCALPHA);
                        }
                    }

                    if (the_display.GetDeviceInfo()->AdamiLightingSupported()) {
                        switch (ii >> 6) {
                        case 9:
                        case 10:
                        case 18:
                        case 19:
                        case 20:
                        case 21:
                            // People texture page — use dest-colour src-colour blend for Adami lighting.
                            SET_RENDER_STATE(D3DRENDERSTATE_SRCBLEND, D3DBLEND_DESTCOLOR);
                            SET_RENDER_STATE(D3DRENDERSTATE_DESTBLEND, D3DBLEND_SRCCOLOR);

                            SET_RENDER_STATE(D3DRENDERSTATE_ALPHABLENDENABLE, UC_TRUE);
                            SET_RENDER_STATE(D3DRENDERSTATE_TEXTUREMAPBLEND, D3DTBLEND_DECAL);

                            break;
                        }
                    }
                }
                break;
            }
        }
    }

    // Flush queued polys before re-sorting pages.
    // uc_orig: POLY_ClearAllPages (fallen/DDEngine/Source/poly.cpp)
    extern void POLY_ClearAllPages(void);
    POLY_ClearAllPages();

    // Sort pages by texture handle to minimise D3D state changes during rendering.
    for (int ii = 0; ii < POLY_NUM_PAGES; ii++) {
        PageOrdered[ii] = false;
    }

    SLONG pos = 0;
    while (pos < POLY_NUM_PAGES) {
        int ii;
        for (ii = 0; ii < POLY_NUM_PAGES; ii++) {
            if (!PageOrdered[ii])
                break;
        }
        if (ii == POLY_NUM_PAGES) {
            // All done.
            break;
        }

        POLY_Page[ii].pTheRealPolyPage = &(POLY_Page[ii]);

        PageOrder[pos++] = ii;
        PageOrdered[ii] = true;
        LPDIRECT3DTEXTURE2 tex = POLY_Page[ii].RS.GetTexture();
        PolyPage* pPolyPage = &(POLY_Page[ii]);

        if (tex != NULL) {
            for (ii++; ii < POLY_NUM_PAGES; ii++) {
                if (POLY_Page[ii].RS.GetTexture() == tex) {
                    // If this page has the same texture AND same render states, make it a
                    // "ghost" page (all polys sent to it go to the real page instead).
                    if (POLY_Page[ii].RS.IsSameRenderState(&(pPolyPage->RS))) {
                        POLY_Page[ii].pTheRealPolyPage = pPolyPage;
                    } else {
                        POLY_Page[ii].pTheRealPolyPage = &(POLY_Page[ii]);
                        PageOrder[pos++] = ii;
                    }
                    PageOrdered[ii] = true;
                }
            }
        }
    }

    // iPolyNumPagesRender is defined in poly.cpp (not yet migrated).
    // uc_orig: iPolyNumPagesRender (fallen/DDEngine/Source/poly.cpp)
    extern int iPolyNumPagesRender;
    iPolyNumPagesRender = pos;

    RenderStates_OK = UC_TRUE;
}
