#ifndef ASSETS_XLAT_STR_H
#define ASSETS_XLAT_STR_H

#include "engine/platform/uc_common.h"

// uc_orig: MAX_STRING_SPACE (fallen/Headers/xlat_str.h)
#define MAX_STRING_SPACE (8192)
// uc_orig: MAX_STRINGS (fallen/Headers/xlat_str.h)
#define MAX_STRINGS (256)

// uc_orig: XCTL_JUMP (fallen/Headers/xlat_str.h)
#define XCTL_JUMP (1)
// uc_orig: XCTL_PUNCH (fallen/Headers/xlat_str.h)
#define XCTL_PUNCH (2)
// uc_orig: XCTL_KICK (fallen/Headers/xlat_str.h)
#define XCTL_KICK (3)
// uc_orig: XCTL_ACTION (fallen/Headers/xlat_str.h)
#define XCTL_ACTION (4)
// uc_orig: XCTL_LEFT (fallen/Headers/xlat_str.h)
#define XCTL_LEFT (5)
// uc_orig: XCTL_RIGHT (fallen/Headers/xlat_str.h)
#define XCTL_RIGHT (6)
// uc_orig: XCTL_START (fallen/Headers/xlat_str.h)
#define XCTL_START (7)
// uc_orig: XCTL_SELECT (fallen/Headers/xlat_str.h)
#define XCTL_SELECT (8)
// uc_orig: XCTL_SPACE (fallen/Headers/xlat_str.h)
#define XCTL_SPACE (9)
// uc_orig: XCTL_ENTER (fallen/Headers/xlat_str.h)
#define XCTL_ENTER (10)
// uc_orig: XCTL_CAM_FIRST (fallen/Headers/xlat_str.h)
#define XCTL_CAM_FIRST (11)
// uc_orig: XCTL_RUN (fallen/Headers/xlat_str.h)
#define XCTL_RUN (12)
// uc_orig: XCTL_CAM_HIGH (fallen/Headers/xlat_str.h)
#define XCTL_CAM_HIGH (13)
// uc_orig: XCTL_CAM_LOW (fallen/Headers/xlat_str.h)
#define XCTL_CAM_LOW (14)
// uc_orig: XCTL_CAM_ESC (fallen/Headers/xlat_str.h)
#define XCTL_CAM_ESC (15)
// uc_orig: XCTL_CAM_CONTINUE (fallen/Headers/xlat_str.h)
#define XCTL_CAM_CONTINUE (16)

// String IDs for all localizable UI text.
// uc_orig: X_THIS_LANGUAGE_IS (fallen/Headers/xlat_str.h)
#define X_THIS_LANGUAGE_IS (0)
// uc_orig: X_PRESS_TO_CONTINUE (fallen/Headers/xlat_str.h)
#define X_PRESS_TO_CONTINUE (1)
// uc_orig: X_GAME_OVER (fallen/Headers/xlat_str.h)
#define X_GAME_OVER (2)
// uc_orig: X_CAR_LOCKED (fallen/Headers/xlat_str.h)
#define X_CAR_LOCKED (3)
// uc_orig: X_AMMO (fallen/Headers/xlat_str.h)
#define X_AMMO (4)
// uc_orig: X_GUN (fallen/Headers/xlat_str.h)
#define X_GUN (5)
// uc_orig: X_HEALTH (fallen/Headers/xlat_str.h)
#define X_HEALTH (6)
// uc_orig: X_FUSE_SET (fallen/Headers/xlat_str.h)
#define X_FUSE_SET (7)
// uc_orig: X_ENTER_VEHICLE (fallen/Headers/xlat_str.h)
#define X_ENTER_VEHICLE (8)
// uc_orig: X_USE_BIKE (fallen/Headers/xlat_str.h)
#define X_USE_BIKE (9)
// uc_orig: X_PICK_UP (fallen/Headers/xlat_str.h)
#define X_PICK_UP (10)
// uc_orig: X_GRAB_CABLE (fallen/Headers/xlat_str.h)
#define X_GRAB_CABLE (11)
// uc_orig: X_SEARCHING (fallen/Headers/xlat_str.h)
#define X_SEARCHING (12)
// uc_orig: X_COMPLETE (fallen/Headers/xlat_str.h)
#define X_COMPLETE (13)
// uc_orig: X_QUIT_TO_MAIN_MENU (fallen/Headers/xlat_str.h)
#define X_QUIT_TO_MAIN_MENU (14)
// uc_orig: X_RESTART_AUTOSAVE (fallen/Headers/xlat_str.h)
#define X_RESTART_AUTOSAVE (15)
// uc_orig: X_LEVEL_COMPLETE (fallen/Headers/xlat_str.h)
#define X_LEVEL_COMPLETE (16)
// uc_orig: X_START (fallen/Headers/xlat_str.h)
#define X_START (17)
// uc_orig: X_LOAD_GAME (fallen/Headers/xlat_str.h)
#define X_LOAD_GAME (18)
// uc_orig: X_SAVE_GAME (fallen/Headers/xlat_str.h)
#define X_SAVE_GAME (19)
// uc_orig: X_OPTIONS (fallen/Headers/xlat_str.h)
#define X_OPTIONS (20)
// uc_orig: X_GRAPHICS (fallen/Headers/xlat_str.h)
#define X_GRAPHICS (21)
// uc_orig: X_SOUND (fallen/Headers/xlat_str.h)
#define X_SOUND (22)
// uc_orig: X_MUSIC (fallen/Headers/xlat_str.h)
#define X_MUSIC (23)
// uc_orig: X_QUALITY (fallen/Headers/xlat_str.h)
#define X_QUALITY (24)
// uc_orig: X_VOLUME (fallen/Headers/xlat_str.h)
#define X_VOLUME (25)
// uc_orig: X_STEREO (fallen/Headers/xlat_str.h)
#define X_STEREO (26)
// uc_orig: X_MONO (fallen/Headers/xlat_str.h)
#define X_MONO (27)
// uc_orig: X_REVERSE_STEREO (fallen/Headers/xlat_str.h)
#define X_REVERSE_STEREO (28)
// uc_orig: X_DRIVERS (fallen/Headers/xlat_str.h)
#define X_DRIVERS (29)
// uc_orig: X_RESOLUTION (fallen/Headers/xlat_str.h)
#define X_RESOLUTION (30)
// uc_orig: X_REFLECTIONS (fallen/Headers/xlat_str.h)
#define X_REFLECTIONS (31)
// uc_orig: X_DRAW_DISTANCE (fallen/Headers/xlat_str.h)
#define X_DRAW_DISTANCE (32)
// uc_orig: X_SHADOWS (fallen/Headers/xlat_str.h)
#define X_SHADOWS (33)
// uc_orig: X_DETAIL (fallen/Headers/xlat_str.h)
#define X_DETAIL (34)
// uc_orig: X_HIGH (fallen/Headers/xlat_str.h)
#define X_HIGH (35)
// uc_orig: X_MEDIUM (fallen/Headers/xlat_str.h)
#define X_MEDIUM (36)
// uc_orig: X_LOW (fallen/Headers/xlat_str.h)
#define X_LOW (37)
// uc_orig: X_EXIT (fallen/Headers/xlat_str.h)
#define X_EXIT (38)
// uc_orig: X_OKAY (fallen/Headers/xlat_str.h)
#define X_OKAY (39)
// uc_orig: X_CANCEL (fallen/Headers/xlat_str.h)
#define X_CANCEL (40)
// uc_orig: X_CONTROLS (fallen/Headers/xlat_str.h)
#define X_CONTROLS (41)
// uc_orig: X_KEYPAD (fallen/Headers/xlat_str.h)
#define X_KEYPAD (42)
// uc_orig: X_KEYBOARD (fallen/Headers/xlat_str.h)
#define X_KEYBOARD (43)
// uc_orig: X_JOYSTICK (fallen/Headers/xlat_str.h)
#define X_JOYSTICK (44)
// uc_orig: X_JOYPAD (fallen/Headers/xlat_str.h)
#define X_JOYPAD (45)
// uc_orig: X_SPACE (fallen/Headers/xlat_str.h)
#define X_SPACE (46)
// uc_orig: X_ENTER (fallen/Headers/xlat_str.h)
#define X_ENTER (47)
// uc_orig: X_JUMP (fallen/Headers/xlat_str.h)
#define X_JUMP (48)
// uc_orig: X_KICK (fallen/Headers/xlat_str.h)
#define X_KICK (49)
// uc_orig: X_PUNCH (fallen/Headers/xlat_str.h)
#define X_PUNCH (50)
// uc_orig: X_ACTION (fallen/Headers/xlat_str.h)
#define X_ACTION (51)
// uc_orig: X_LEFT (fallen/Headers/xlat_str.h)
#define X_LEFT (52)
// uc_orig: X_RIGHT (fallen/Headers/xlat_str.h)
#define X_RIGHT (53)
// uc_orig: X_FORWARDS (fallen/Headers/xlat_str.h)
#define X_FORWARDS (54)
// uc_orig: X_BACKWARDS (fallen/Headers/xlat_str.h)
#define X_BACKWARDS (55)
// uc_orig: X_SELECT (fallen/Headers/xlat_str.h)
#define X_SELECT (56)
// uc_orig: X_LOOK_AROUND (fallen/Headers/xlat_str.h)
#define X_LOOK_AROUND (57)
// uc_orig: X_RUN (fallen/Headers/xlat_str.h)
#define X_RUN (58)
// uc_orig: X_CAMERA (fallen/Headers/xlat_str.h)
#define X_CAMERA (59)
// uc_orig: X_BADGE (fallen/Headers/xlat_str.h)
#define X_BADGE (60)
// uc_orig: X_COLLECTED (fallen/Headers/xlat_str.h)
#define X_COLLECTED (61)
// uc_orig: X_COMPLETED (fallen/Headers/xlat_str.h)
#define X_COMPLETED (62)
// uc_orig: X_FAILED (fallen/Headers/xlat_str.h)
#define X_FAILED (63)
// uc_orig: X_SCORE (fallen/Headers/xlat_str.h)
#define X_SCORE (64)
// uc_orig: X_PRIMARY (fallen/Headers/xlat_str.h)
#define X_PRIMARY (65)
// uc_orig: X_SECONDARY (fallen/Headers/xlat_str.h)
#define X_SECONDARY (66)
// uc_orig: X_OBJECTIVES (fallen/Headers/xlat_str.h)
#define X_OBJECTIVES (67)
// uc_orig: X_MAP (fallen/Headers/xlat_str.h)
#define X_MAP (68)
// uc_orig: X_WEAPONS (fallen/Headers/xlat_str.h)
#define X_WEAPONS (69)
// uc_orig: X_SHOTGUN (fallen/Headers/xlat_str.h)
#define X_SHOTGUN (70)
// uc_orig: X_AK (fallen/Headers/xlat_str.h)
#define X_AK (71)
// uc_orig: X_GRENADE (fallen/Headers/xlat_str.h)
#define X_GRENADE (72)
// uc_orig: X_EXPLOSIVES (fallen/Headers/xlat_str.h)
#define X_EXPLOSIVES (73)
// uc_orig: X_KNIFE (fallen/Headers/xlat_str.h)
#define X_KNIFE (74)
// uc_orig: X_BASEBALL_BAT (fallen/Headers/xlat_str.h)
#define X_BASEBALL_BAT (75)
// uc_orig: X_BOMB (fallen/Headers/xlat_str.h)
#define X_BOMB (76)
// uc_orig: X_KEYCARD (fallen/Headers/xlat_str.h)
#define X_KEYCARD (77)
// uc_orig: X_FILE (fallen/Headers/xlat_str.h)
#define X_FILE (78)
// uc_orig: X_FLOPPY_DISK (fallen/Headers/xlat_str.h)
#define X_FLOPPY_DISK (79)
// uc_orig: X_CROWBAR (fallen/Headers/xlat_str.h)
#define X_CROWBAR (80)
// uc_orig: X_GAS_MASK (fallen/Headers/xlat_str.h)
#define X_GAS_MASK (81)
// uc_orig: X_WRENCH (fallen/Headers/xlat_str.h)
#define X_WRENCH (82)
// uc_orig: X_VIDEO (fallen/Headers/xlat_str.h)
#define X_VIDEO (83)
// uc_orig: X_GLOVES (fallen/Headers/xlat_str.h)
#define X_GLOVES (84)
// uc_orig: X_WEED_AWAY (fallen/Headers/xlat_str.h)
#define X_WEED_AWAY (85)
// uc_orig: X_RED_CAR_KEYS (fallen/Headers/xlat_str.h)
#define X_RED_CAR_KEYS (86)
// uc_orig: X_BLUE_CAR_KEYS (fallen/Headers/xlat_str.h)
#define X_BLUE_CAR_KEYS (87)
// uc_orig: X_GREEN_CAR_KEYS (fallen/Headers/xlat_str.h)
#define X_GREEN_CAR_KEYS (88)
// uc_orig: X_BLACK_CAR_KEYS (fallen/Headers/xlat_str.h)
#define X_BLACK_CAR_KEYS (89)
// uc_orig: X_WHITE_CAR_KEYS (fallen/Headers/xlat_str.h)
#define X_WHITE_CAR_KEYS (90)
// uc_orig: X_WIRECUTTERS (fallen/Headers/xlat_str.h)
#define X_WIRECUTTERS (91)
// uc_orig: X_ARE_YOU_SURE (fallen/Headers/xlat_str.h)
#define X_ARE_YOU_SURE (92)
// uc_orig: X_CRIME_RATE (fallen/Headers/xlat_str.h)
#define X_CRIME_RATE (93)
// uc_orig: X_ARRESTED (fallen/Headers/xlat_str.h)
#define X_ARRESTED (94)
// uc_orig: X_COMPANY (fallen/Headers/xlat_str.h)
#define X_COMPANY (95)
// uc_orig: X_COPYING_GLOBAL_MEDIA (fallen/Headers/xlat_str.h)
#define X_COPYING_GLOBAL_MEDIA (96)
// uc_orig: X_COPYING_LOCAL_MEDIA (fallen/Headers/xlat_str.h)
#define X_COPYING_LOCAL_MEDIA (97)
// uc_orig: X_COPYING_PROGRAM (fallen/Headers/xlat_str.h)
#define X_COPYING_PROGRAM (98)
// uc_orig: X_REQUIRES_WINDOWS (fallen/Headers/xlat_str.h)
#define X_REQUIRES_WINDOWS (99)
// uc_orig: X_COMPONENT (fallen/Headers/xlat_str.h)
#define X_COMPONENT (100)
// uc_orig: X_INST_FILE (fallen/Headers/xlat_str.h)
#define X_INST_FILE (101)
// uc_orig: X_FILE_GROUP (fallen/Headers/xlat_str.h)
#define X_FILE_GROUP (102)
// uc_orig: X_ERROR_OCCURRED (fallen/Headers/xlat_str.h)
#define X_ERROR_OCCURRED (103)
// uc_orig: X_REQUIRES_DIRECTX (fallen/Headers/xlat_str.h)
#define X_REQUIRES_DIRECTX (104)
// uc_orig: X_FAILED_TO_INITIALIZE (fallen/Headers/xlat_str.h)
#define X_FAILED_TO_INITIALIZE (105)
// uc_orig: X_REQUIRES_VGA (fallen/Headers/xlat_str.h)
#define X_REQUIRES_VGA (106)
// uc_orig: X_URBAN_CHAOS_SETUP (fallen/Headers/xlat_str.h)
#define X_URBAN_CHAOS_SETUP (107)
// uc_orig: X_EDITOR (fallen/Headers/xlat_str.h)
#define X_EDITOR (108)
// uc_orig: X_AMBIENT (fallen/Headers/xlat_str.h)
#define X_AMBIENT (109)
// uc_orig: X_STARS (fallen/Headers/xlat_str.h)
#define X_STARS (110)
// uc_orig: X_MOON (fallen/Headers/xlat_str.h)
#define X_MOON (111)
// uc_orig: X_PEOPLE (fallen/Headers/xlat_str.h)
#define X_PEOPLE (112)
// uc_orig: X_PUDDLES (fallen/Headers/xlat_str.h)
#define X_PUDDLES (113)
// uc_orig: X_DIRT (fallen/Headers/xlat_str.h)
#define X_DIRT (114)
// uc_orig: X_MIST (fallen/Headers/xlat_str.h)
#define X_MIST (115)
// uc_orig: X_RAIN (fallen/Headers/xlat_str.h)
#define X_RAIN (116)
// uc_orig: X_SKYLINE (fallen/Headers/xlat_str.h)
#define X_SKYLINE (117)
// uc_orig: X_CON_INCREASED (fallen/Headers/xlat_str.h)
#define X_CON_INCREASED (118)
// uc_orig: X_STR_INCREASED (fallen/Headers/xlat_str.h)
#define X_STR_INCREASED (119)
// uc_orig: X_STA_INCREASED (fallen/Headers/xlat_str.h)
#define X_STA_INCREASED (120)
// uc_orig: X_REF_INCREASED (fallen/Headers/xlat_str.h)
#define X_REF_INCREASED (121)
// uc_orig: X_LOAD_UCM (fallen/Headers/xlat_str.h)
#define X_LOAD_UCM (122)
// uc_orig: X_SCANNER (fallen/Headers/xlat_str.h)
#define X_SCANNER (123)
// uc_orig: X_TRACK (fallen/Headers/xlat_str.h)
#define X_TRACK (124)
// uc_orig: X_CHARACTER (fallen/Headers/xlat_str.h)
#define X_CHARACTER (125)
// uc_orig: X_GAMMA (fallen/Headers/xlat_str.h)
#define X_GAMMA (126)
// uc_orig: X_RESET_DEFAULT (fallen/Headers/xlat_str.h)
#define X_RESET_DEFAULT (127)
// uc_orig: X_STR (fallen/Headers/xlat_str.h)
#define X_STR (128)
// uc_orig: X_CON (fallen/Headers/xlat_str.h)
#define X_CON (129)
// uc_orig: X_DEX (fallen/Headers/xlat_str.h)
#define X_DEX (130)
// uc_orig: X_STA (fallen/Headers/xlat_str.h)
#define X_STA (131)
// uc_orig: X_NO_CONES_HIT (fallen/Headers/xlat_str.h)
#define X_NO_CONES_HIT (132)
// uc_orig: X_NUM_CONES_HIT (fallen/Headers/xlat_str.h)
#define X_NUM_CONES_HIT (133)
// uc_orig: X_RESUME_LEVEL (fallen/Headers/xlat_str.h)
#define X_RESUME_LEVEL (134)
// uc_orig: X_RESTART_LEVEL (fallen/Headers/xlat_str.h)
#define X_RESTART_LEVEL (135)
// uc_orig: X_ABANDON_GAME (fallen/Headers/xlat_str.h)
#define X_ABANDON_GAME (136)
// uc_orig: X_TEXTURE_MAP (fallen/Headers/xlat_str.h)
#define X_TEXTURE_MAP (137)
// uc_orig: X_PERSPECTIVE (fallen/Headers/xlat_str.h)
#define X_PERSPECTIVE (138)
// uc_orig: X_BILINEAR (fallen/Headers/xlat_str.h)
#define X_BILINEAR (139)
// uc_orig: X_TIME_PENALTY (fallen/Headers/xlat_str.h)
#define X_TIME_PENALTY (140)
// uc_orig: X_LEVEL_LOST (fallen/Headers/xlat_str.h)
#define X_LEVEL_LOST (141)
// uc_orig: X_GAME_PAUSED (fallen/Headers/xlat_str.h)
#define X_GAME_PAUSED (142)
// uc_orig: X_GET_DOWN (fallen/Headers/xlat_str.h)
#define X_GET_DOWN (143)
// uc_orig: X_CANT_SHOOT_COP (fallen/Headers/xlat_str.h)
#define X_CANT_SHOOT_COP (144)
// uc_orig: X_HEY_WHY_HITTING (fallen/Headers/xlat_str.h)
#define X_HEY_WHY_HITTING (145)
// uc_orig: X_CANT_SHOOT_UNARMED (fallen/Headers/xlat_str.h)
#define X_CANT_SHOOT_UNARMED (146)
// uc_orig: X_CRIME_RATE_REDUCED (fallen/Headers/xlat_str.h)
#define X_CRIME_RATE_REDUCED (147)
// uc_orig: X_GAME_SAVED (fallen/Headers/xlat_str.h)
#define X_GAME_SAVED (148)
// uc_orig: X_CRINKLES (fallen/Headers/xlat_str.h)
#define X_CRINKLES (149)
// uc_orig: X_COLOUR_DEPTH (fallen/Headers/xlat_str.h)
#define X_COLOUR_DEPTH (150)
// uc_orig: X_CIVSDEAD_WARNING_1 (fallen/Headers/xlat_str.h)
#define X_CIVSDEAD_WARNING_1 (151)
// uc_orig: X_CIVSDEAD_WARNING_2 (fallen/Headers/xlat_str.h)
#define X_CIVSDEAD_WARNING_2 (152)
// uc_orig: X_CIVSDEAD_WARNING_3 (fallen/Headers/xlat_str.h)
#define X_CIVSDEAD_WARNING_3 (153)
// uc_orig: X_CIVSDEAD_WARNING_4 (fallen/Headers/xlat_str.h)
#define X_CIVSDEAD_WARNING_4 (154)
// uc_orig: X_WON_KILLED (fallen/Headers/xlat_str.h)
#define X_WON_KILLED (155)
// uc_orig: X_WON_ARRESTED (fallen/Headers/xlat_str.h)
#define X_WON_ARRESTED (156)
// uc_orig: X_WON_AT_LARGE (fallen/Headers/xlat_str.h)
#define X_WON_AT_LARGE (157)
// uc_orig: X_WON_BONUS_FOUND (fallen/Headers/xlat_str.h)
#define X_WON_BONUS_FOUND (158)
// uc_orig: X_WON_BONUS_MISSED (fallen/Headers/xlat_str.h)
#define X_WON_BONUS_MISSED (159)
// uc_orig: X_WON_TIMETAKEN (fallen/Headers/xlat_str.h)
#define X_WON_TIMETAKEN (160)
// uc_orig: X_WON_BESTTIME (fallen/Headers/xlat_str.h)
#define X_WON_BESTTIME (161)
// uc_orig: X_WON_MUCKYTIME (fallen/Headers/xlat_str.h)
#define X_WON_MUCKYTIME (162)
// uc_orig: X_YES (fallen/Headers/xlat_str.h)
#define X_YES (163)
// uc_orig: X_NO (fallen/Headers/xlat_str.h)
#define X_NO (164)
// uc_orig: X_EMPTY (fallen/Headers/xlat_str.h)
#define X_EMPTY (165)
// uc_orig: X_3DCARD (fallen/Headers/xlat_str.h)
#define X_3DCARD (166)
// uc_orig: X_USE_PRIMARY (fallen/Headers/xlat_str.h)
#define X_USE_PRIMARY (167)
// uc_orig: X_USE_SECONDARY (fallen/Headers/xlat_str.h)
#define X_USE_SECONDARY (168)
// uc_orig: X_USE_SOFTWARE (fallen/Headers/xlat_str.h)
#define X_USE_SOFTWARE (169)
// uc_orig: X_NUM_COLOURS (fallen/Headers/xlat_str.h)
#define X_NUM_COLOURS (170)
// uc_orig: X_16BIT (fallen/Headers/xlat_str.h)
#define X_16BIT (171)
// uc_orig: X_24BIT (fallen/Headers/xlat_str.h)
#define X_24BIT (172)
// uc_orig: X_DO_NOT_SHOW (fallen/Headers/xlat_str.h)
#define X_DO_NOT_SHOW (173)
// uc_orig: X_MILES_SETUP (fallen/Headers/xlat_str.h)
#define X_MILES_SETUP (174)
// uc_orig: X_SELECT_SOUND (fallen/Headers/xlat_str.h)
#define X_SELECT_SOUND (175)
// uc_orig: X_BUTTON (fallen/Headers/xlat_str.h)
#define X_BUTTON (176)
// uc_orig: X_CREDITS (fallen/Headers/xlat_str.h)
#define X_CREDITS (177)
// uc_orig: X_BONUS_MISSION_UNLOCKED (fallen/Headers/xlat_str.h)
#define X_BONUS_MISSION_UNLOCKED (178)
// uc_orig: X_JUMP_CAM (fallen/Headers/xlat_str.h)
#define X_JUMP_CAM (179)

// Returns the translated string for the given string ID, written into the
// provided buffer (or an internal static buffer if xlat_dest is NULL).
// uc_orig: XLAT_str (fallen/Headers/xlat_str.h)
CBYTE* XLAT_str(SLONG string_id, CBYTE* xlat_dest = 0);

// Returns a direct pointer into the translation pool for the given string ID.
// Does not copy — caller must not modify the returned string.
// uc_orig: XLAT_str_ptr (fallen/Headers/xlat_str.h)
CBYTE* XLAT_str_ptr(SLONG string_id);

// Loads the translation file at the given path and builds the string table.
// uc_orig: XLAT_load (fallen/Headers/xlat_str.h)
void XLAT_load(CBYTE* fn);

// Populates default control remapping strings (space, enter, etc.).
// Must be called after XLAT_load.
// uc_orig: XLAT_init (fallen/Headers/xlat_str.h)
void XLAT_init();

#endif // ASSETS_XLAT_STR_H
